usi-verification-and-security/opensmt

src/parsers/smt2new/CMakeLists.txt, src/tsolvers/lrasolver/LRA_Interpolator.cpp, src/tsolvers/lrasolver/LRA_Interpolator.h
Small changes in code to make it compatible with gcc 4.8.
Added minimum version of BISON to cryptic error messages when people try to use older version.
=> Fixing compatibility issues

src/cnfizers/Cnfizer.C, src/smtsolvers/CoreSMTSolver.C, src/smtsolvers/CoreSMTSolver.h, src/smtsolvers/SimpSMTSolver.C, src/smtsolvers/Theory.C
fix for issue #7 
Explicitly declaring boolean variables from inside UF terms to the SAT solver.
=> fixing issue #7

docs/abstract.bib, docs/abstract.tex, docs/easychair.cls
Hi Martin & Matteo,
I made a quick pass on the short documentation which we will send to SMT workshop proceedings.  Have a look please, and let me know if you find something strange!
=> Changes to the short description for SMT-COMP 2019

src/api/MainSolver.C, src/api/MainSolver.h, src/proof/PGInterpolator.C, src/simplifiers/BoolRewriting.cpp, src/simplifiers/BoolRewriting.h, test/unit/test_simplifyAssignment.cpp
Added an aggressive version of lifting conjunctions and disjunctions. New version ensures that no disjunction is a child of disjunction, and the same of conjunctions.
Added a more aggressive interpolation simplification based on this.
Refactoring.
=> Added even stronger simplification of interpolants. Refactoring

src/logics/BVLogic.C, src/logics/CUFLogic.C, src/logics/Logic.C, src/logics/Logic.h, src/minisat/mtl/Map.h, src/pterms/PtStore.C, src/simplifiers/LA.C, src/symbols/SymStore.C, src/symbols/SymStore.h, src/tsolvers/lasolver/LASolver.cpp, src/tsolvers/lasolver/Simplex.cpp
What the title says plus tiny clean-ups.
=> Avoiding repeated work when creating and looking up symbols in symbol table

src/smtsolvers/Theory.C
This is a quick fix to include information for a top-level implied literal that is needed for proof building and has been missing in the case where top-level literal is deduced from a LIA split.
=> Update of PRODUCE_PROOF version of handling LIA split

src/tsolvers/lasolver/LASolver.cpp, src/tsolvers/lasolver/Simplex.cpp, test/unit/test_Simplex.cpp
Fixes #51 and #52.
Fixed the computation of the final value of the symbolic variable delta.
Fixed retrieving value of a negative term.
=> Fix of issues regarding retrieving values from satisfying assignments

regression/generic/boolean-distinct.smt2, regression/generic/boolean-distinct.smt2.expected.out, src/cnfizers/Tseitin.cc, src/cnfizers/Tseitin.h, src/logics/Logic.cc, src/logics/Logic.h, test/unit/CMakeLists.txt, test/unit/test_LogicMkTerms.cc
=> Fixed the messy handling of distinct predicate

regression/generic/check-sat-after-unsat.smt2, regression/generic/check-sat-after-unsat.smt2.expected.out, src/api/MainSolver.cc, src/cnfizers/Cnfizer.cc, src/common/Alloc.h, src/smtsolvers/CoreSMTSolver.cc, src/smtsolvers/CoreSMTSolver.h, src/smtsolvers/Theory.cc, src/tsolvers/lasolver/Delta.cc, src/tsolvers/lasolver/Delta.h, src/tsolvers/lasolver/LABounds.cc, src/tsolvers/lasolver/LABounds.h, src/tsolvers/lasolver/LARefs.h, src/tsolvers/lasolver/LASolver.cc, src/tsolvers/lasolver/LASolver.h, src/tsolvers/lasolver/LAVar.h, src/tsolvers/lasolver/LAVarMapper.cc, src/tsolvers/lasolver/LAVarMapper.h, src/tsolvers/lasolver/Simplex.cc, src/tsolvers/lasolver/Simplex.h, src/tsolvers/liasolver/LIASolver.cc, src/tsolvers/lrasolver/LRAModel.cc, src/tsolvers/lrasolver/LRAModel.h, src/tsolvers/lrasolver/LRASolver.cc, src/tsolvers/lrasolver/LRASolver.h, test/unit/CMakeLists.txt, test/unit/test_Bounds.cc
This PR contains the following changes:
- Refactoring in LRA solver regarding Delta and iterating over LA variables
- Proper cleaning of LA solver and its components
- Fix for issue #60 when re-running check-sat command on solver in UNSAT state.
=> Recent refactoring in LRA solver and fixing some issues

examples/test_lia.cc, src/api/MainSolver.cc, src/api/MainSolver.h, src/logics/Logic.cc, src/logics/Logic.h, src/logics/Theory.cc, src/logics/Theory.h, src/logics/UFLRATheory.h, src/sorts/SStore.h, src/symbols/SymStore.cc, src/symbols/Symbol.h
I am suggesting some small cleanup in MainSolver and Symbol.
This has been inspired by me accidentally calling MainSolver::solve method instead of MainSolver::check and getting weird results.
@aehyvari Let me know what you think about this.
=> Tiny cleanup

.circleci/config.yml, ci/run_travis_commands.sh
Here's an idea how we could do CI in CircleCI.
=> Add support for CircleCI

test/CMakeLists.txt
=> GTest: Bump version to 1.11.0

src/simplifiers/LA.cc, src/simplifiers/LA.h
Includes formatting changes, some code modernisation and removal of unused methods.
=> LA: Cleanup of a helper class LAExpression

test/unit/CMakeLists.txt, test/unit/test_Splitting.cc
This PR provides a unit test that catches the problem fixed in PR #303.
=> Unit test for correct printing of terms

src/logics/Logic.cc, src/logics/Logic.h, src/models/Model.cc, test/unit/test_FunctionTemplate.cc
=> [Logic] Unify template instantiation

src/bin/Interpret.cc, src/logics/BVLogic.cc, src/logics/BVLogic.h, src/logics/CUFLogic.cc, src/logics/CUFLogic.h, src/logics/LIALogic.cc, src/logics/LIALogic.h, src/logics/LRALogic.cc, src/logics/LRALogic.h, src/logics/Logic.cc, src/logics/Logic.h, src/pterms/PtStore.cc, test/unit/test_EnodeStore.cc, test/unit/test_Explain.cc, test/unit/test_FunctionTemplate.cc, test/unit/test_Ites.cc, test/unit/test_LogicMkTerms.cc, test/unit/test_Model.cc, test/unit/test_Rewriting.cc, test/unit/test_Splitting.cc, test/unit/test_SubstitutionBreaker.cpp, test/unit/test_TheorySimplifications.cc, test/unit/test_UFInterpolation.cc
PR suggests a refactoring for declareSort and some API changes that throw in case of errors.
=> [logic] declareSort refactoring

src/logics/Logic.cc, src/logics/Logic.h
A function for obtaining the sort from, say, an arithmetic sum symbol.  I plan to use this in interpolation in methods which are not aware of the exact arithmetic logic.
=> [logic] Helper for determining the sort for operators

examples/CMakeLists.txt, src/logics/BVLogic.cc, src/logics/BVLogic.h, src/logics/CUFLogic.cc
After some refactoring, the examples for BVLogic stopped working.
This PR attempts to fix these problems. The examples seem to be running again.
=> Fix sort of BVLogic and related problems

src/rewriters/Rewriter.h, src/simplifiers/LA.cc
I found these assertions descriptive and helpful when combining the arithmetic logics.  If we like them, we could put them to the code.
=> Rewriting assertions

src/logics/BVLogic.h, src/rewriters/DivModRewriter.h, src/rewriters/Rewriter.h, src/tsolvers/lasolver/LASolver.h, src/tsolvers/lasolver/LAVarMapper.cc, test/unit/test_LIAInterpolation.cc
Here's yet another tiny cleanup PR.  I think I implemented most of the changes in another PR and forgot to put this one in.
=> Whitespaces and vectors

Changelog.md
Updates the changelog with the recent changes visible to the user.
=> Changelog update

src/bin/Interpret.cc, src/logics/Logic.cc, src/logics/Logic.h, src/symbols/SymStore.cc, src/symbols/SymStore.h, src/symbols/Symbol.h, test/unit/test_Egraph.cpp, test/unit/test_EnodeStore.cc, test/unit/test_Explain.cc, test/unit/test_LogicMkTerms.cc, test/unit/test_Model.cc, test/unit/test_Splitting.cc, test/unit/test_SubstitutionBreaker.cpp, test/unit/test_TheorySimplifications.cc, test/unit/test_UFInterpolation.cc
This PR cleans further the symbol interface by forbidding (incorrect) changes to symbols once created.
=> Symbol cleanup

src/logics/UFLATheory.cc
Replaces the check `containsUF` with a much simpler check `isPureArithmeticEquality`.
The former check can be pretty expensive as it requires the instantiation and run of a `TermVisitor`, and it is run on every equality encountered.
The latter check is much simpler and directly checks the children of the equality. This is only possible because the subterms are purified before the equalities are considered.
The difference is not noticeable on small benchmarks, but makes a huge difference on the few extremely large benchmarks in `QF_UFLRA/cpachecker-bmc-svcomp14`. Unfortunately we still run into the blow-up when creating interface clauses in these examples. (but now we run into the blow-up much sooner! :) ).
=> UFLA: Simplify preprocessing

regression_models/bin/run-and-validate.sh, regression_models/bin/run-tests.sh
Catch scrambler parsing errors and notify user that CI scripts run model regression tests.
=> regression: model validation script fixes

regression/run-test-notiming.sh, src/bin/Interpret.cc, src/smtsolvers/LookaheadSMTSolver.cc, src/smtsolvers/LookaheadSMTSolver.h, src/smtsolvers/LookaheadSplitter.cc, src/smtsolvers/LookaheadSplitter.h
This PR fixes critical memory leaks in lookahead code.
=> Lookahead memleak fix

src/simplifiers/LA.cc
Just a small code duplication that I found.
=> LAExpression: Avoid unnecessary code duplication

src/api/MainSolver.cc, src/api/MainSplitter.cc, src/bin/Interpret.cc, src/bin/Interpret.h
Some minor fixes after the refactoring PR.
=> MainSolver: API fixes

src/proof/PG.h, src/proof/PGBuild.cc, src/proof/PGHelp.cc
This PR finishes some style cleanup + constness that were mentioned in #423 and #424, but were not part of the big ProofGraph/Interpolation rewrite.
=> ProofGraph: Fix code style

src/logics/CUFTheory.cc, src/logics/LATheory.h, src/logics/Theory.cc, src/logics/Theory.h, src/logics/UFLATheory.cc, src/logics/UFTheory.cc
=> Theory: Encapsulate substitution-based simplification

src/smtsolvers/LookaheadSMTSolver.cc, src/smtsolvers/LookaheadSMTSolver.h
@BritikovKI Here are some suggestions for the PR.  I tried to make the commits logical so you can check what I mean hopefully easier.
=> Lookahead experimentation suggestions

src/bin/opensmt.cc, src/smtsolvers/CoreSMTSolver.cc, src/smtsolvers/SimpSMTSolver.cc
Separate PR for verbose option adding
=> Adding verbose option

src/minisat/core/SolverTypes.h, src/smtsolvers/CoreSMTSolver.cc, src/smtsolvers/CoreSMTSolver.h
Updating glue during analysis. This is default for most SAT solvers.
=> Update glue on analyze

src/logics/ArithLogic.cc
The method mkTimes is general a does a lot of work to ensure the term is properly
normalized. When we wnat to negate en xisting term, we know that it is
already normalized, so we can compute the proper result much cheaper
than passing multiplying it by -1 and letting mkTimes do the
simplifications.
=> ArithLogic: Avoid expensive call to mkTimes in mkNeg

src/parallel/LookaheadSplitter.h, src/parallel/MainSplitter.cc, src/parallel/MainSplitter.h, src/parallel/ScatterSplitter.cc, src/parallel/ScatterSplitter.h, src/parallel/Splitter.h, src/parallel/SplitterInterpret.h, src/parallel/opensmtSplitter.cc
Splitter*:  Refactor channel usage to adapt template class of Channel
=> Splitter*:  Refactor channel usage to adapt template class of Channel

src/logics/ArrayTheory.cc, src/logics/ArrayTheory.h, src/tsolvers/ArrayTHandler.cc, src/tsolvers/ArrayTHandler.h, src/tsolvers/TSolver.h, src/tsolvers/axdiffsolver/ArraySolver.cc, src/tsolvers/axdiffsolver/ArraySolver.h, src/tsolvers/egraph/Egraph.h
Some suggestions on the array PR
=> Array solver style fixes

src/tsolvers/axdiffsolver/ArraySolver.cc, src/tsolvers/axdiffsolver/ArraySolver.h
=> Array solver style fixes 2

.circleci/config.yml, src/parallel/CMakeLists.txt
This PR,
print stats of the PTPLib in color, it'd help to track compilation process easily on ci, aws through docker,...
BTW, I was just tracking compilation process and here is how it looks like:
=> CMakeLists-parallel: Print stats of the PTPLib in color

.clang-files, src/rewriters/ArithmeticEqualityRewriter.h, src/rewriters/DistinctRewriter.cc, src/rewriters/DistinctRewriter.h, src/rewriters/DivModRewriter.h, src/rewriters/Rewriter.h, src/rewriters/Substitutor.h
Reformat more files in our codebase.
=> Rewriters: Apply clang-format

Changelog.md
This PR adds changelog entries for the upcoming release 2.4.2
=> Changelog: Update for version 2.4.2

src/logics/ArithLogic.cc
In application that issues a large number of simple queries, such as Spacer algorithm, a surprisingly large portion of the runtime is spend in ArithLogic::mkPlus.
One reason is the usage of VecMap which is quite memory-intensive data structure.  With the proposed change we hope to reduce the amount of memory allocated and deallocated in each call to mkPlus.  Less work with memory should lead to better overall performance.
=> ArithLogic: Avoid VecMap usage in mkPlus

bin/opensmt.C, src/bin/opensmt.cc, src/minisat/core/Main.C, src/minisat/simp/Main.C, src/minisat/utils/System.h, src/parallel/opensmtSplitter.cc
Signed-off-by: Maciej Barć <xgqt@gentoo.org>
=> use fpu_control only on glibc

.clang-format, src/rewriters/Rewriter.h, src/tsolvers/lasolver/Tableau.cc
Updates to our clang-format configurations.
=> clang-format: Update configuration

src/rewriters/ArithmeticEqualityRewriter.h, src/smtsolvers/CoreSMTSolver.cc, src/tsolvers/lasolver/LASolver.cc, src/tsolvers/lasolver/LASolver.h, src/tsolvers/lasolver/Simplex.cc, src/tsolvers/lasolver/Simplex.h, test/unit/test_Simplex.cc
Remove unused code.
Small simplifications of existing code.
=> Small cleanup in various places

AUTHORS, LICENSE
=> updated authors (also in the license)

src/proof/PGHelp.cc
This PR replaces the current implementation of top-down (parents before child) topological order for resolution proof. New implementation uses a simple DFS traversal from root, marking child only after its parents are processed.
The advantage of the new implementation is that it does not need the information about resolvents of each proof node.
Regarding performance, anectodal evidence from Golem shows that the new implementation performs better, because it does not need to traverse resolvents of each node, which is a std::set.
=> ProofGraph: Simplify computation of topological order

docker/Dockerfile, docker/build_image.sh
Allows the use of various base images (such as SMT-COMP).
=> Parametrized Dockerfile's base and provided a helper script

Changelog.md, README.md, examples/CMakeLists.txt
Some places were missed with the switch to C++20 ..
=> switch to C++20 (contd.)

Changelog.md
We should probably go for a new major release because the API changed.
=> Upd. changelog

CMakeLists.txt, src/bin/opensmt.cc, src/options/SMTConfig.cc, src/options/SMTConfig.h
This is the branch to fix #800 , #777, #769 
It introduces changes to CLI processing, and also reintroduces help message and versioning
=> Command Line Rework: rework of the command line interface
