src/tsolvers/lrasolver/Polynomial.cpp

Attached is the comparison of performance on latest SMT-LIB QF_LRA. It is not always better, but overall, there is a tiny performance gain and one more problem solved.
[comparison.pdf](https://github.com/usi-verification-and-security/opensmt/files/3201830/comparison.pdf)

Reserving more memory in advance in important operation of LRA solver

---

src/tsolvers/lrasolver/Polynomial.cpp
src/tsolvers/lrasolver/Polynomial.h
src/tsolvers/lrasolver/Tableau.cpp

After pivot operation, tableau representation needs to be updated.
Instead of allocating and deallocating helper vector in each iteration, allocate once at the before the loop and reuse.
See the attached comparison.
[comparison_reuse.pdf](https://github.com/usi-verification-and-security/opensmt/files/3211800/comparison_reuse.pdf)

Small improvement by re-using memory in important loop

---

src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.C

Fixed possible assertion of equality to Egraph solver when its state is already unsatisfiable.
Also, the information about the state after assertion is stored as bool, no need for l_bool, since only l_False (conflict) and l_Undef (no conflict) were used.

Fixing issue #19

---

src/logics/Logic.C

I used std::unordered_set as a cache. Would you prefer the Map from minisat?
Also, returning using move in this case is not a good idea, it prevents Return Value Optimization.

Fixing method Logic::getNestedBoolRoots to traverse the PTerm structure as a DAG and not as a tree.

---

src/api/MainSolver.C
src/api/MainSolver.h
src/cnfizers/Cnfizer.C
src/cnfizers/Cnfizer.h
src/logics/LALogic.h
src/logics/LRATheory.C
src/logics/Logic.C
src/logics/Logic.h
src/logics/Theory.h
src/simplifiers/BoolRewriting.cpp

Various small changes to prevent unnecessary work. Please review carefully and report anything suspicious.
Moved dealing with nested booleans to Cnfizer, the MainSolver no longer knows about that.
LALogic avoids this altogether.

Small optimizations in preprocessing and small cleanup

---

CMakeLists.txt
src/logics/LIATheory.C
src/logics/LRATheory.C
src/logics/Logic.C

Changed caching for traversing PTerm DAG in Logic::propagatePartitionMask and Logic::simplifyTree.
Removed PRODUCE_PROOF macro from one place in Logic.
Set the default build type to Release, so users of OpenSMT library do not have to thing about that.

Small updates

---

src/options/SMTConfig.C
src/options/SMTConfig.h
src/smtsolvers/CoreSMTSolver.C
src/tsolvers/LASolver.C
src/tsolvers/LASolver.h
src/tsolvers/LRATHandler.C
src/tsolvers/LRATHandler.h
src/tsolvers/TSolver.h
src/tsolvers/TSolverHandler.h
src/tsolvers/UFTHandler.C
src/tsolvers/UFTHandler.h
src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.C
src/tsolvers/egraph/EnodeStore.h
src/tsolvers/lrasolver/LABounds.C
src/tsolvers/lrasolver/LABounds.h
src/tsolvers/lrasolver/LAVar.C
src/tsolvers/lrasolver/LAVar.h
src/tsolvers/lrasolver/LRASolver.C
src/tsolvers/lrasolver/LRASolver.h

This adds the possibility for the SAT solver to ask theory solver for suggested polarity once SAT solver has picked new decision variable.
New interface method is provided with implementations for LRA solver and UF solver.
The measured impact in LRA is huge, in UF is small but still positive.

Polarity suggestion

---

src/api/Interpret.C
src/api/Interpret.h
src/common/StringMap.h
src/logics/Logic.C
src/options/SMTConfig.C
src/options/SMTConfig.h
src/parsers/smt2new/smt2newparser.yy
src/symbols/SymStore.C

This PR contains two main changes.
1. New hash function for strings that works much better for similar names (like var12 vs var21).
2. Deleting AST nodes after processing so that the memory is released and not kept throughout the whole solving process.
2b. In addition vector is used to store children in AST node instead of list, as vector has lower memory footprint.

Optimizing pre-solving phase

---

src/api/Interpret.C
src/tsolvers/lrasolver/LRAModel.cpp
src/tsolvers/lrasolver/LRAModel.h

This PR contains a fix for a relatively big memory leak introduced by me in bb2e8bbd.
The problem is that one Vec was not cleaned properly.
In addition, this PR contains a fix for an old minor leak from pre-solving phase where char* was not freed on all program paths.

Fixing memory leak introduced in recent changes to LRA solver

---

regression_itp/dec-far1.smt2
src/api/Interpret.C
src/proof/PGInterpolator.C

Fixes #43 
The theory solver was cleaned before interpolating in a theory clause node, but not after.
This caused problems with respect to recent changes (#40 ) as the invariant were not preserved by the subsequent call to interpolation engine.
The fix is to clean the TSolver after interpolant computation in every theory leave of the proof.
It is a good practice to clean up after one-self.

Fixing issue #43 - proper cleanup of TSolver after interpolating at theory clause nodes in the proof

---

README.md
regression_itp/dec-far2.smt2
src/logics/LALogic.cc
src/parsers/smt2new/CMakeLists.txt
src/tsolvers/lrasolver/LRA_Interpolator.cc

This PR contains the implementation of complete algorithm for computing decomposition of the vector of Farkas coefficients based on the basis of the kernel of the matrix of coefficients of A-local  variables.
Additionaly, it contains 2 hotfixes: Increasing the version of BISON required for compilation and fixing an incorrect use of Pterm& instead of PTRef.
I also modified the code of SimplifyConst::simplify a little bit to avoid unnecessary copying of vector of arguments.

Update in LRA decomposition

---

src/api/Interpret.cc
src/logics/Logic.cc
src/logics/Theory.cc
src/logics/Theory.h
src/tsolvers/lasolver/LABounds.cc
src/tsolvers/lasolver/LABounds.h

Fixes for 3 sources of possible memory leaks:
- Dealing with sorts in the Interpreter
- Allocators inheriting from RegionAllocator allocating objects possibly containing pointers to dynamically allocated data. This includes PushFrameAllocator and LABoundAllocator.
The fix for allocators is done by remembering references to allocated objects and then destructing  them properly when needed.
Fixes #69 and #70

Small fixes of memory leaks

---

regression/generic/pre-logic.smt2.expected.out
src/api/Interpret.cc
src/bin/CMakeLists.txt
src/bin/opensmt.cc

Added success notification message to multiple Interpreter commands where it was missing.
Added a command line option to use front-end in pipe-like manner, since the behaviour of the readline library is not compatible with the trace executor of SMT-COMP in the incremental track.
Also, the printing of git commit hash been removed, as nobody is really using it and (hopefully) we will have a proper release versioning soon.

Small fixes to incrementality frontend

---

src/api/MainSolver.cc
src/api/MainSolver.h
src/cnfizers/Cnfizer.cc
src/cnfizers/Cnfizer.h
src/cnfizers/Tseitin.h
src/logics/Logic.cc
src/pterms/PtStructs.cc
src/pterms/PtStructs.h
src/simplifiers/BoolRewriting.cc
src/simplifiers/BoolRewriting.h
src/smtsolvers/CoreSMTSolver.cc
test/unit/CMakeLists.txt
test/unit/test_LogicMkTerms.cc
test/unit/test_Rewriting.cpp

Main optimization is in the caching inside CNFizer where formulas inserted in frames other than level 0 are checked also for level 0, to avoid asserting redundant clauses to the SAT solver.
Functions related to rewriting terms before cnfization have been polished, Logic::mkAnd has been changed to reflect Logic::mkOr and to catch situations where arguments contain two complementary terms.

Optimizations aiming at improving incremental mode.

---

src/logics/Logic.cc

Method Logic::conjoinItes relies on an invariant that given a formula, all of its subterms have lower ID than the root. This is true in most cases since to create a term, its subterms must have already been created. But ITEs are handled in a special way: they are represented by a variable that has a definition and this definition contains that variable as a subterm, hence has higher ID than the variable.
Thus is the root term passed to this method is an ITE variable, the invariant is broken. 
This PR handles the special case.

Fix for a broken invariant where the whole formula is ITE on the top-level

---

.travis.yml
CMakeLists.txt
README.md
cmake_modules/FindLibEdit.cmake
src/api/CMakeLists.txt
src/api/Interpret.cc

I discussed this with Natasha Sharygina at the Facebook TAV event in 2018, but managed to completely forget about this for a long time ...
Currently, OpenSMT has a "hard" dependency against `readline`, however `readline` is a [GPL licensed library](https://tiswww.case.edu/php/chet/readline/rltop.html).
A great reference for this is [here](https://en.wikipedia.org/wiki/GNU_Readline):
> GNU Readline is notable for being a free software library which is licensed under the GNU General Public License (GPL) ... linking to ... Readline requires the entire combined resulting application to be licensed under the GPL when distributed, to comply with section 5 of the GPL.
Basically, while the _code_ of OpenSMT might be MIT licensed, if anyone is linking against a _binary build_ of OpenSMT (e.g., …

Provide support for linking OpenSMT against 'libedit'

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/api/CMakeLists.txt

Issue #132 requested the ability to build "only" the static libraries.
This PR adds support to:
- *turning off* building static libraries (`-DBUILD_STATIC_LIBS:BOOL=OFF`)
- *turning off* building shared libraries (`-DBUILD_SHARED_LIBS:BOOL=OFF`)
- *turning off* building the final executable (`-DBUILD_EXECUTABLES:BOOL=OFF`)
By default, *all* are `ON`, which means that the current behaviour is unchanged. You *cannot* build executables *without* building static libraries -- this will error-out when running `cmake`.
```
cmake \
-G Ninja \
-DBUILD_STATIC_LIBS:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DBUILD_EXECUTABLES:BOOL=OFF \
-DPACKAGE_TESTS:BOOL=OFF ..
```
```
cmake \
-G Ninja \
-DBUILD_STATIC_LIBS:BOOL=OFF \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DBUILD_EXECUTABLES:BOOL=OFF \ …
```

Providing support for building shared libraries/static libraries/target executables in isolation

---

src/api/Interpret.cc

When compiling, I see these _warnings_:
```
[12/16] Linking CXX shared library src/api/libopensmt2.so
src/api/CMakeFiles/api.dir/Interpret.cc.o: In function `Interpret::interpPipe()':
Interpret.cc:(.text+0x856c): warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
[16/16] Linking CXX executable src/bin/opensmt
src/api/libapi_static.a(Interpret.cc.o): In function `Interpret::interpPipe()':
Interpret.cc:(.text+0x856c): warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
```
Compiler (stock CentOS 8):
```
$ gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```

Fixing warning about the use of a deprecated interface (sys_errlist)

---

.travis.yml

This PR add a MacOS build to Travis CI.
We add only a single configuration for MacOS using Debug build and Clang compiler, because the MacOS is slower than Linux build. This is caused by the need to upgrade Bison, which requires an update of the Homebrew in the VM of the build.

enabling MacOS build in Travis CI

---

CMakeLists.txt
src/api/Interpret.cc
src/api/Interpret.h
src/bin/opensmt.cc

This PR addresses issue #135 
Since the command line interaction library (Readline or Editline) is needed only when executable is being built, we can remove the dependency in situations where executable is not required.

Restricting dependency on Readline/Editline to the situation when executable is needed

---

src/common/FastRational.h
test/unit/test_Rationals.cpp

Fixes #159 
For INT32_MIN in type int32_t the negation operation cannot be represented and `- INT32_MIN` is undefined behaviour if the type of the variable is int32_t.
For the discussion and proposed solution see [this post](https://stackoverflow.com/questions/12231560/correct-way-to-take-absolute-value-of-int-min).
Additionally, the constructor of FastRational that was not normalizing the numerator and denumerator has been removed since could break the invariant of the type.

Fixing undefined behaviour in absVal

---

src/tsolvers/lasolver/CMakeLists.txt
src/tsolvers/lasolver/Simplex.cc
src/tsolvers/lasolver/Tableau.cc

The reason is to improve the runtime for common debugging of LA examples since some of the checks in Simplex are very expensive and are called very often.

Moving some expensive debugging checks in Simplex solver behind a special macro that is OFF by default

---

src/common/FastRational.cc
src/common/FastRational.h

This PR fixes a bug in FastRational::get_den() and unifies the style of methods `gdc, lcm, divexact, fastrat_fdiv_q` with the rest of operations over FastRationals

Small refactoring of some operations in FastRationals

---

src/logics/LALogic.cc
src/logics/LALogic.h
src/logics/Logic.cc
src/logics/Logic.h
src/minisat/mtl/Vec.h
src/models/Model.cc
test/unit/test_TheorySimplifications.cc

This PR moves the code used in the Logic API `std::vector` =>  minisat `vec` conversion  directly to minisat `vec`'s constructor.

std::vector to minisat vec conversion

---

src/common/OsmtInternalException.h
src/logics/LALogic.cc
src/logics/LALogic.h
src/logics/LIALogic.cc
src/logics/LIALogic.h
src/tsolvers/lasolver/LASolver.cc
test/unit/CMakeLists.txt
test/unit/test_LIAStrengthening.cc

This is my attempt at creating strengthened bounds for LIA already during the term creation.
Part of it is also a refactoring of the normalization of sums in LRA Logic.

Normalizing LIA inequalities with bound tightening already in Logic

---

src/models/ModelBuilder.cc
test/unit/test_Model.cc

After recent changes in handling ITEs, whole ITE term can now be substituted during the preprocessing.
The Model building code needs to be updated to reflect that.

Fix of handling substituted ITEs in Model building

---

src/smtsolvers/TheoryInterpolator.h
src/tsolvers/egraph/UFInterpolator.cc
src/tsolvers/egraph/UFInterpolator.h
src/tsolvers/lrasolver/FarkasInterpolator.cc
src/tsolvers/lrasolver/FarkasInterpolator.h
src/tsolvers/lrasolver/LRASolver.cc
test/unit/test_LRAInterpolation.cc

This PR is a follow-up of #183 and aims to better define how information about partitioning of terms is passed to the Theory Interpolators. 
This partitioning information can be global, derived from the partitioning of the whole SMT query, or it can be local, derived just from the partitioning of the theory conflict passed to the interpolator.
These can be different, as terms that are shared globally across partitions can be local within a single theory conflict.
This PR includes just refactoring of the current code, with no change in the functionality, but it better separates the Interpolator classes from the rest of the code, which allows for easier unit testing.
In the future we could also change how the partitioning information is computed---the global partitioning information can be …

Refactoring of colouring information in Theory Interpolation

---

src/bin/Interpret.cc

Currently the solver throws an exception if an interpolation is attempted but the solver is not in UNSAT state. In the interpreter we can check this and report an error to the user instead of throwing the exception.
Resolves #96 (when the option to produce interpolants is set properly before the set-logic command).

Fail gracefully when (get-interpolants) command is encountered in an SMT-LIB script, but the solver is not in UNSAT state.

---

src/common/Alloc.h
src/common/CMakeLists.txt
src/common/osmtinttypes.h
src/minisat/core/SolverTypes.h
src/minisat/mtl/Map.h
src/minisat/mtl/Vec.h
src/minisat/utils/Options.h
src/minisat/utils/System.h
src/tsolvers/lasolver/LARefs.h

This PR fixes a problem where on case-insensitive systems the opensmt's installed header called IntTypes.h gets confused with the system header inttypes.h causing builds to fail.  The suggested fix is to change the name of the header file.

A more macos filesystem friendly name for our IntTypes wrapper

---

.travis.yml

Temporary solution, until we figure out how to continue with CI.
Reaction to this: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Disabling OSX build on Travis, because of the new Travis policy

---

.travis.yml
CMakeLists.txt
benchmark/CMakeLists.txt

Fixed settings to force the disabling of building unit tests in google-benchmark also for the first configuration.
Also, at least CMake 3.11 is required for fetching the external project the way we do.

Fix google-benchmark options

---

src/common/FastRational.h
src/tsolvers/lasolver/Simplex.cc

This PR contains 2 small changes:
1. Adds helper methods to detect if a FastRational is positive or negative and uses these methods instead of more expensive explicit comparison with 0.
2. Pre-allocates exact space for the Simplex explanation, thus avoiding potential intermediate re-allocations.

Tiny optimizations in Simplex

---

src/models/Model.cc

This PR fixes the problem in Modell where a C++ reference to `Pterm` is kept and used in a loop where new terms can be created. This can potentially cause a segmentation fault if reallocation of the term table happens inside the loop.

Fix manipulation with Pterms in Model

---

src/bin/Interpret.cc

As pointed out in #213 the output of a single interpolant was not conforming to the standard.  This pull-request should fix the single-inteprolant printing as well.

Fixes the presentation of a single interpolant

---

src/logics/LALogic.cc

This PR introduces defensive behaviour in `LALogic::mkNumDiv` to not just rely on correct input, but throw exception if the arguments do not meet the requirements.

Throwing non-linear exception on division by non-constant

---

src/smtsolvers/TheoryInterpolator.h

Apple clang version 12.0.0 complains that currently the iterator in question needs to copy a value.  I believe that's correct.  This PR fixes the iteration to use const & instead of copying.

Do not copy termColors in iteration

---

src/common/FastRational.h
src/tsolvers/lasolver/Delta.h
src/tsolvers/lasolver/Polynomial.h
src/tsolvers/lasolver/Tableau.cc

Playing with [heaptrack](https://github.com/KDE/heaptrack) I noticed that when we need to fall back to `mpq` representation of rationals, OpenSMT makes a huge amount of small allocations and deallocations related to handling this representation.
While trying to investigate that, I found a couple of places in the code where we make unnecessary copies of `FastRationals` or create unnecessary temporaries. This PR proposes some changes to avoid that.

Avoid unnecessary allocations and deallocation of GNU MPs

---

src/cnfizers/Cnfizer.cc
src/cnfizers/Cnfizer.h
src/logics/Logic.cc
src/logics/Logic.h
test/unit/CMakeLists.txt
test/unit/test_LRALogicMkTerms.cc
test/unit/test_LogicMkTerms.cc

In `Logic` we have methods `isLit` and `isAtom` with custom implementation.
I believe `isLit` should just rely on `isAtom`.

Small refactoring of Logic::isLit

---

src/cnfizers/Cnfizer.cc
src/cnfizers/Cnfizer.h
src/cnfizers/Tseitin.cc

Now that we're cleaning `Cnfizer` I also added some small things that maybe could be in line with the spirit of the original PR.
- use list comprehension for loops when possible
- make a pass on uniforming the indentation style in if - else -constructs and white spaces in function calls
- rename the current frame variable more appropriately
- Clean the constructor (and destructor) a little

Unifying style, small refactorings

---

src/cnfizers/Cnfizer.cc
src/cnfizers/Cnfizer.h
src/common/TreeOps.h
test/unit/test_LogicMkTerms.cc

As a preparation for dealing with distinct in the pre-processing phase, this PR pulls the method to retrieve top-level formulae out of Cnfizer. This is needed to distinguish top-level distincts from other distincts in the formula.
This PR also fixes TermVisitor to prevent duplicate calls to `previsit` for the same term if it returned `false` the first time.

Refactoring of retrieving top-level formulae

---

src/common/FastRational.h
test/unit/test_Rationals.cpp

Thanks to an example from @MasoudAsadzade, we discovered that the representation invariant for `FastRational` could have been violated within operations `negate` and `inverse`.
That is, we could have end up with a FastRational that fits into word representation, but actually had only the mpq representation.
This PR fixes this problem and adds the corresponding checks.

Enforce representation invariant of FastRational

---

src/options/SMTConfig.cc
src/options/SMTConfig.h
src/proof/PG.h

When OpenSMT is used as a library, the project has access to enable simplification of the interpolants immediately after they are computed through the field `SMTConfig::simplify_interpolant`.
However, this option cannot be set from SMT-LIB script using the standard `(set-option)` command.
This PR removes the field and instead uses the standard way to set and retrieve the value of this option.

Enabling the option to simplify interpolants also in SMT-LIB scripts

---

src/itehandler/IteToSwitch.h
src/proof/PGBuild.cc
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/GhostSMTSolver.cc
src/tsolvers/THandler.cc
src/tsolvers/THandler.h
src/tsolvers/TSolverHandler.cc
src/tsolvers/TSolverHandler.h

This PR suggests two small optimizations for improving performance.
The first one is just using smaller underlying type for `class enum ite::type` so it requires less memory.
The second one is caching the information in `THandler` which SAT variables are interesting for theory solvers.
The original check was using `Logic::isTheoryTerm` which is non-trivial. Moreover, this check has been reported for every literal added or removed from SAT trace every time.
The experiments show this amounts to ~3% speed up both in UF and LRA.
[comparison_uf.pdf](https://github.com/usi-verification-and-security/opensmt/files/6566544/comparison_uf.pdf)
[comparison_lra.pdf](https://github.com/usi-verification-and-security/opensmt/files/6566545/comparison_lra.pdf)

Small optimizations

---

src/common/FastRational.h
test/unit/test_Rationals.cpp

I found one more case where a FastRational with `mpq` representation has been created even though it could fit the word representation.
This happened in unary minus operator where if the input is `2^31`, it does not fit word representation, but its negation `-2^31` fits.

Fixed edge case in FastRationals

---

src/tsolvers/lasolver/Polynomial.h
src/tsolvers/lasolver/Tableau.cc
src/tsolvers/lasolver/Tableau.h

[Heaptrack](https://github.com/KDE/heaptrack) identified some parts of OpenSMT making a lot of memory allocations. This PR is the first one in a series attempting to reduce the number of memory allocations.
`Polynomial::merge` is the key method that keeps the Tableau of LASolver in a consistent state and is called quite a number of times.
It uses additional space (storage) to properly merge two polynomials into a new one. However, this additional storage was not re-used as much as it could.
This PR proposes to save this temporary storage in the Tableau, so it can be does not have to be allocated and destroyed repeatedly.
Moreover, the method `Tableau::normalizeRow` was not re-using this storage previously at all, even though  it could.
Both `normalizeRow` and `pivot` now reuse the storage …

Reducing memory allocations - part 1

---

src/tsolvers/lasolver/Polynomial.h
src/tsolvers/lasolver/Simplex.cc

This PR represents part 2 in reducing memory allocations, it builds on top of #255.
It itself has two parts.
One is just avoiding unnecessary copies by using `const &` in a few places where this was missing.
The other one is more important and it tries to avoid allocating a temporary vector of `Term`s in `Polynomial::merge`.
An important note here is that we need to be careful not to end up with lots of polynomials in the `Tableau` with small size but huge capacity. This would blow up in terms of memory usage.
So sometimes we need to shrink them to release unused capacity. The goal of this change is to do that only when necessary.
The experiments show the current version seems to be working well.
[comparison_lra_mem1_mem2.pdf](https://github.com/usi-verification-and-security/opensmt/files/ …

Reduction of memory allocations - part2

---

src/proof/PGMain.cc

A number of methods in proof reduction uses  C's rand() method to randomly decide a choice when all heuristics fail.
This PR seeds the random number generator at the beginning of the reduction algorithm.
It's a workaround that could be improved later (for example by fixing the default choice and removing all the calls to rand()).

Seed global random generator with seed from SMTConfig to ensure reproducible runs.

---

src/proof/PG.h
src/proof/PGHelp.cc
src/proof/PGTransformationAlgorithms.cc

This PR is first in the series of cleaning up proof transformation code.
The goal is to pinpoint and fix an error that I am seeing in CHC benchmarks, where after a reduction iteration a node ends up with both antecedents being the same node. This is something that should not be happening.
This first part contains style changes in two methods: `ProofGraph::mergeClauses` and `ProofGraph::recycleUnits`.

Proof transformations cleanup - part 1 of N

---

src/proof/PG.h
src/proof/PGHelp.cc
test/unit/CMakeLists.txt
test/unit/test_Proof.cc

The implementation of the method has been simplified and assertions for preconditions and postconditions have been added.
Several unit tests have been added to check correctness of the implementation.

Proof transformations cleanup - part 2 of N: Refactor ProofGraph::mergeClauses

---

src/proof/PG.h
src/proof/PGTransformationAlgorithms.cc

This PR contains style fixes for method `ProofGraph::recyclePivotsIter`.
In addition, two separate phases of this method has been identified:
In the first phase, the proof is traversed from bottom to top and redundant nodes are identified. The redundant edge is removed.
In the second phase, the proof is traversed from top to bottom and redundant nodes identified in the previous phase are replaced with their (now single) parent. This can expose more redundant nodes as now some resolutions might not be necessary anymore.
The first phase has been extracted to standalone method `ProofGraph::recyclePivotsIter_RecyclePhase`. The second phase is still kept in the original method unchanged (except the style fixes).
Depends on #262.

Proof transformations cleanup - part 3 of N: ProofGraph::recyclePivotsIter

---

src/proof/PGTransformationAlgorithms.cc
test/unit/test_Proof.cc

This PR adds two unit tests for testing `ProofGraph::recyclePivotsIter`.
The second one shows that it is possible that during this algorithm a situation might occur where a node ends up with antecedents being one and the same node. This follows from the properties of the algorithm and the algorithm can handle it simply by replacing such node with its (single) parent.
At the end of the algorithm, the proof is always in a valid state and there will not be any node with identical parents.
Depends on #263.

Proof transformations cleanup - part 4 of N

---

src/proof/PG.h
src/proof/PGRules.cc
src/proof/PGTransformationAlgorithms.cc
test/unit/test_Proof.cc

This PR deals with cleaning up the method `ProofGraph::proofTransformAndRestructure`.
It adds two unit tests for checking basic functionality of the method, the second one exposing a path in the code that previously triggered error. It is a situation similar to the one in #264, i.e., while restructuring and reducing the proof, the algorithm might run into a situation where a node has identical antecedents. Previously this was reported as an error and the program terminated.
However, as the unit test shows, such a situation can occur for a valid proof as input. The same solution as in #264 can be applied, the algorithm only needs to replace the node with its (single) antecedent and continue as normal.
Apart from this, small style fixes has been applied.
Depends on #264.

Proof transformations cleanup - part 5 of N: ProofGraph::proofTransformAndRestructure

---

src/proof/PGHelp.cc
src/proof/PGTransformationAlgorithms.cc

Beside the original and theory clauses, split clauses and assumptions clauses can now occur as leaves in the proof.

Proof: Relax rules on leaf types

---

regression_itp/uf_local_colors_insufficient.smt2
src/tsolvers/egraph/UFInterpolator.cc
src/tsolvers/egraph/UFInterpolator.h
test/unit/test_UFInterpolation.cc

Because we re-use one theory solver for all theory conflicts, it may happen that the explanation of a conflict depends on a term not present in that particular conflict (but is present in the input formula).
This breaks the invariant assumed before, i.e., that local coloring information is enough to color the `CGraph` (congruence graph representing the explanation).
But even in global coloring information, a term (like `f(x)`) can originally be assigned only color `A` (when present only in partition `A`) while in the `CGraph` we need to color it as `AB` because both `f` and `x` have color `AB`.
This required a small change in the code which was not prepared for such situation.
Added are a regression and a unit test that show this problem, although they are sensitive to the order in which …

Fix crash in UF interpolator

---

src/tsolvers/lasolver/LABounds.cc
src/tsolvers/lasolver/LABounds.h
src/tsolvers/lasolver/LARefs.h
src/tsolvers/lasolver/LASolver.cc

This prevents a memory leak in current implementation of the addition of new bounds after the solver has been initialized.

LASolver: Replace LABoundList in bounds data structure

---

src/tsolvers/lasolver/LABounds.cc

This bug has been introduced recently in 5d1aa9a8.
In the original version, the correct index was not set, if the new bound ended up at the first place in the list of bounds.

LIASolver: Fix incorrect update of bounds after split

---

src/tsolvers/THandler.cc

We currently do not remember reasons for theory propagated literals and lazily re-compute them only when really needed.
The computation backtracks SAT solver before the propagated literal and asserts its negation. This *must* result in conflict from which we extract the reason.
If this operation does not result in conflict, something is broken and we should throw an exception instead of ignoring this.

CoreSMTSolver: Throw exception on error situation

---

src/logics/BVLogic.cc
src/logics/CUFLogic.cc
src/logics/CUFLogic.h
src/logics/LALogic.cc
src/logics/Logic.cc
src/logics/Logic.h
src/proof/PGInterpolator.cc
src/tsolvers/bvsolver/BitBlaster.cc
test/unit/test_Ites.cc
test/unit/test_LogicMkTerms.cc

In many places, when creating terms, the code does not use more compact and readable way of using initializer lists.
This PR represents a small cleanup to use initializer lists where possible and avoid explicit temporary `vec`s.
This should help experimenting with further changes in term creation in the future.

Term creation cleanup

---

src/proof/PGTransformationAlgorithms.cc
test/unit/test_Proof.cc

It is possible that a node marked for removal in
recyclePivotsIter_RecyclePhase will cause one of its children to have
identical antecedents. This is already handled correctly in the
algorithm. Unit test test_recyclePivots_IdenticalAntecedents_AfterPhaseOneReplace shows how
this situation can occur.
Thus, the assertion in recyclePivotsIter does not hold in all circumstances and should be removed.

Proof transformations cleanup - part 6 of N 

---

regression_itp/incremental/inc_itp_theory_prop.smt2
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/Proof.cc
src/smtsolvers/TheoryIF.cc

Not having theory propagation in interpolating mode slows down the solving on some instances significantly.
The motivation for this change were some CHC benchmark where solver during many incremental calls accumulated a lot of binary clauses corresponding to theory propagation in arithmetic theories.
These accumulated clauses were slowing down solving significantly as the SAT solver were trying to reduce the number of learnt clauses before *every* decision, but did not succeed as these were all binary clauses.
The change in the code turned out to be not not complicated at all. The only difficult thing was maintaining specific invariant for learning unary clauses at level 0.
To maintain it, we need to log in the proof derivation of unary clause when theory propagation occurs at level 0.

CoreSMTSolver: Enable theory propagation in interpolating mode

---

regression_models/bin/run-and-validate.sh
regression_models/bin/run-tests.sh

This PR fixes model validator CI scripts so that they return with non-zero value if model is not validated.  It also fixes a bug that resulted in temporary files being deleted even when a flag was given that was supposed to prevent the deletion for easier debugging.

CI: fix model validation to actually report errors

---

src/logics/LALogic.cc
src/logics/LALogic.h
src/logics/LIALogic.cc
src/logics/LIALogic.h
src/logics/LRALogic.cc
src/logics/LRALogic.h
src/logics/Logic.cc
src/logics/Logic.h
test/unit/test_LIALogicMkTerms.cc
test/unit/test_LRALogicMkTerms.cc

Depends on #292.
Resolves #267.
Currently, arithmetic equalities are not normalized, they are created as given, in the same way as equalities for uninterpreted sorts.
This PR adds normalization process to arithmetic equalities on creation, which works almost the same as the normalization for arithmetic inequalities.

Normalize arithmetic equalities.

---

src/logics/Logic.cc

A bug introduced in c5698fbf resulted in no space being printed between a term and its first argument.  This PR fixes the problem.

Fix: print space between a symbol and its first argument

---

.circleci/config.yml

CircleCI already provides a home-brew installation so there's no need for us to explicitly fetch it.
https://circleci.com/docs/2.0/testing-ios/#using-homebrew

[CircleCI] Do not install homebrew in circleci

---

src/bin/opensmt.cc

It looks like in #318 we forget to hide include of headers behind `ifdef`.
I got compilation error on the cluster.
It was most likely not detected because the headers could be found in the standard system paths, but that's not the case in the cluster.

Do not include headers of line editing library when disabled

---

src/common/FastRational.cc
src/common/FastRational.h

Gets rid of C-style init of temporaries, by removing temporaries altogether.

Mpq cleanup

---

src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.cc
src/tsolvers/egraph/EnodeStore.cc

Enodes for negative boolean terms are needed only when these terms are
themselves arguments of other enodes. In most cases, we do not need to
create enodes for negative boolean terms.
Positive boolean terms still need enodes since these are used for theory
deductions.

Egraph: Avoid creating unnecessary enodes for boolean terms

---

src/logics/LALogic.cc
src/logics/LALogic.h
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LAVarMapper.cc
src/tsolvers/lasolver/LAVarMapper.h
test/unit/test_LRALogicMkTerms.cc

`isNegated` implementation seems to fit better in the theory solver.  This PR suggests it to be implemented in `LAVarMapper` that holds the mapping between `PTRef`s and `LAVar`s and uses `isNegated` in an `assert`.

[logic] Moved LALogic::isNegated to LAVarMapper::isNegated

---

src/logics/Logic.cc

The member `Logic::subst_num` has been removed recently (#332) so now the current state does not compile with STATISTICS on.

Logic: Fix compilation with STATISTICS on

---

src/api/PartitionManager.h
src/common/Global.h
src/common/TreeOps.h
src/rewriters/DistinctRewriter.h
src/rewriters/Rewriter.h
src/tsolvers/IDLTHandler.h
src/tsolvers/RDLTHandler.h
src/tsolvers/TSolver.h
src/tsolvers/lasolver/LASolver.h

This represents a first batch of trivial cases where parameter is not used. The goal is to eventually enable -Wunused-parameter.

Remove some unused parameters

---

src/logics/CUFLogic.cc
src/logics/CUFLogic.h

`CUFStr` sort is apparently not used anywhere.
Not sure what its original function was.

CUFLogic: Remove apparently unused sort

---

src/tsolvers/egraph/Enode.h
src/tsolvers/egraph/EnodeStore.cc
src/tsolvers/egraph/EnodeStore.h

The small changes are: 
* Passing `ERef`s by value instead of by reference.
* Do not insert constant terms into signature map. Signatures are only important for detecting congruence and constants cannot become congruent since they have no children.
* Early detection of signature-based equality by true equality.
I got 1% speedup on QF_UF, which may be just noise, but I'd like to think it's more than that :)

Tiny cleanup in Egraph

---

regression/divmod/div-incorrect.smt2
regression/divmod/div-incorrect.smt2.expected.out
regression/divmod/div_1.smt2
regression/divmod/div_2.smt2
regression/divmod/div_3.smt2
regression/divmod/mod-incorrect.smt2
regression/divmod/mod-incorrect.smt2.expected.out
regression/divmod/mod_1.smt2
regression/divmod/mod_2.smt2
regression/divmod/mod_3.smt2
regression/divmod/mod_4.smt2
regression/divmod/nested-div.smt2
regression/divmod/nested-mod.smt2
src/bin/Interpret.cc
src/logics/ArithLogic.cc
src/logics/Logic.cc
src/logics/Logic.h
src/options/SMTConfig.cc
src/options/SMTConfig.h

For now we temporarily enable div and mod by default in LIA logic.
The goal is to add minimal support for non-linear arithmetic and then
allow these operations in non-linear logic only.

LIA: Remove the extended signature flag

---

src/logics/Logic.cc
src/logics/Logic.h
src/symbols/SymStore.cc
src/symbols/SymStore.h
src/tsolvers/egraph/EnodeStore.cc

Changes in this PR:
* Remove the information about interpreted symbols from `Logic`. This information is stored in `SymbolStore` and was duplicated in `Logic`.
* Pass the `interpreted` flag directly when requesting new symbol from `SymbolStore`, do not set it up afterwards.
* Clean up a few functions regarding inquiring whether something is interpreted or uninterpreted.

Logic: Refactor functionality regarding interpreted/uninterpreted symbols

---

src/api/MainSolver.cc
src/bin/Interpret.cc
src/logics/ArithLogic.h
src/logics/BVLogic.h
src/logics/CUFLogic.h
src/logics/Logic.cc
src/logics/Logic.h
src/sorts/SStore.cc
src/sorts/SStore.h
test/unit/CMakeLists.txt
test/unit/test_Sorts.cc

This PR makes the building blocks for indexed sorts (e.g. `(_ BitVec 32)`) available through `Logic` API.  In addition it implements the printing of sorts such parametric sorts.

Indexed sorts

---

src/logics/Logic.cc

If the template does not have any arguments, the only possible
instantiation is its body, there is no need to call the substitutor,
as it will never change the formula.

Logic: Small optimization in template instantiation

---

src/tsolvers/egraph/Egraph.h

I don't see any reason now why the `Egraph` should be backtracking in destructor.
QF_UF SMT-LIB benchmarks are fine with this change.

Egraph: Do not backtrack on destruction

---

src/tsolvers/TSolver.h
src/tsolvers/egraph/Egraph.h
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h
src/tsolvers/stpsolver/STPSolver.h
src/tsolvers/stpsolver/STPSolver_implementations.hpp

The method `TSolver::print` is not doing anything in any of the theory
solvers, I believe we should remove it.

TSolvers: Remove useless method

---

src/logics/ArithLogic.cc

When computing substitutions from top-level arithmetic equalities, it
can happen that multiple substitutions for the same variable are
possible.
Before we just used the first one we encountered.
With this change, if we later encounter a different possible substition
with a constant, we use that one.
This should simplify the formula more.
Another possibility is to compare the complexity of the current and
alternative substitution and pick the less complex one (an example
metric would be the number of terms in the polynomial).
That I leave for future investigation.

Arith: Substitute variable by a constant when possible

---

src/tsolvers/THandler.cc
src/tsolvers/TSolver.cc
src/tsolvers/TSolver.h
src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.cc
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h
src/tsolvers/stpsolver/STPSolver.h
src/tsolvers/stpsolver/STPSolver_implementations.hpp
test/unit/test_Egraph.cpp

This PR contains two parts:
* Introduce a separate method `getReason` in `TSolver`. This cleans up the method in THandler a bit and allows us to remove the boolean parameter from `TSolver::getConflict` (which was mostly ignored anyway).
* Related to the first part, the collection and printing of statistics is cleaned up a bit as well. There are more things that could be done, but I hope this is a good start.

TSolver: Cleanup of reason computation and statistics 

---

.circleci/config.yml
src/api/MainSolver.cc
src/api/MainSolver.h
src/api/Opensmt.cc
src/api/Opensmt.h
src/itehandler/IteToSwitch.h
src/logics/CUFLogic.cc
src/logics/CUFLogic.h
src/logics/CUFTheory.cc
src/logics/SubstLoopBreaker.cc
src/logics/SubstLoopBreaker.h
src/logics/UFLATheory.cc
src/logics/UFTheory.cc
src/proof/PG.h
src/proof/PGInterpolator.cc
src/simplifiers/BoolRewriting.cc
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/CoreSMTSolver.h
src/tsolvers/THandler.cc
src/tsolvers/UFLATHandler.cc
src/tsolvers/lasolver/Matrix.h
src/tsolvers/stpsolver/STPSolver_implementations.hpp

This PR fixes a couple of places where compiler warns on unused parameter and enables the flag in CI runs.
There are a few places where it is not clear if the parameter should be removed completely or not.

Enable warnings on unused parameters

---

.circleci/config.yml
benchmark/performance/perf_RationalEfficiency.cc
src/common/Timer.h
src/logics/BVLogic.cc
src/logics/BVLogic.h
src/logics/CUFLogic.cc
src/logics/CUFLogic.h
src/logics/Logic.h
src/logics/LogicFactory.h
src/tsolvers/bvsolver/Bvector.h

`Wextra` subsumes `Wunused-parameter`.
I exclude `Wignored-qualifiers` for now, as we have quite a few of those.
We should discuss if we enable also that one (I vote "yes").

Enable more compiler warnings

---

regression_models/instances/name_clash.smt2
regression_models/instances/name_clash2.smt2
regression_models/instances/name_clash3.smt2
src/bin/Interpret.cc

Model validator does not like when a formal argument of function
definition has the same name as a variable already defined in the model.
To work around this limitation, this patch adds a small post-processing
that checks for such name clashes in the model and renames the formal
parameters in problematic function definitions.
This is an alternative proposal to #381.

Interpret: Add model post-processing to avoid name clashes

---

src/tsolvers/lasolver/LABounds.cc
src/tsolvers/lasolver/LABounds.h
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h
src/tsolvers/lasolver/Simplex.h
src/tsolvers/lasolver/Tableau.cc
test/unit/CMakeLists.txt
test/unit/test_LASolverIncrementality.cc

We aleady have a mechanism for adding new atoms that deals with LIA
splits. However, those atoms are special in the way that there are new
bounds on an existing variable.
This mechanism is generalized to allow bounds on arbitrary expressions
to be added dynamically.
The main issue is that new row being added to a tableaux must be
normalized, since he variables in the new expression might not be
nonbasic variables at the moment of addition.
Apart from that, we need to ensure that LASolver's data structure are
ready for dynamically added bounds of a new variable not seen at the
init stage.
The rest seems to be working nicely thanks for the mechanism of
QUASI_BASIC variables.

LASolver: Prepare for adding new atoms on-the-fly

---

src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.cc
src/tsolvers/egraph/EnodeStore.cc
test/unit/CMakeLists.txt
test/unit/test_Egraph.cc

Egraph is sensitive to backtracking and needs to undo the made changes
exactly. The important thing is to maintain the invariants of signatures
and use-vectors. Adding new terms to Egraph after initialization causes
problems for maintaining the invariants when backtracking happens.
The solution is inspired by the approach of Yices. For these newly added
terms, we remember on the backtracking stack that we need to re-analyze
them on backtracking to maintain the invariants.
Re-analysis means that we remove these terms from the signature and
use-vectors data structures if they are the representative. After the
solver has backtracked, these terms are re-introduced to these
data-structures, if they are still the representative of their class.
One problem is that it is still not entirely clear …

Egraph: Introduce mechanism for dealing with dynamicly added terms

---

src/smtsolvers/CoreSMTSolver.h
src/smtsolvers/TheoryIF.cc
src/tsolvers/THandler.cc
src/tsolvers/THandler.h
src/tsolvers/TSolverHandler.cc
src/tsolvers/TSolverHandler.h

In order to implement model-based theory combination, we need to generalize our current mechanism of split clauses used currently only for LIA splits.
Instead of a single binary clause, we need to allow solvers to communicate any clause (not just binary) and any number of them. In our proposed implementation we need 3 clauses of which 2 are binary and 1 is ternary.
However, we still need to properly maintain invariants of the SAT solver.
For example, if the new split clause should actually propagate one of its literals, we need to backtrack to the point where it would have been propagated if the clause had already existed.

Generalize split clauses

---

src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h

When Simplex model needs fixing because of integer domain, let's be a bit more clever than just branching on the first variable we find.
There are a couple of heuristics that could be used, most-infeasible branching seems like a good one.
It considers all integer variables that needs fixing and chooses the one with largest distance from an integer point (i.e., minimum from the two distances to the two closest points: floor and ceiling).

LIA: Use most-infeasible branching heuristic

---

examples/test-bv.cc
examples/test-cuf.cc
examples/test17_ex2CADE_CUF.cc
examples/test18_ex2CADE_glue_BV-CUF.cc
examples/test2.cc
examples/test_lra_value.cc
src/bin/Interpret.cc
src/logics/ArithLogic.cc
src/logics/Logic.cc
src/logics/Logic.h
src/logics/SubstLoopBreaker.cc
src/tsolvers/lasolver/Matrix.cc
src/tsolvers/lasolver/Matrix.h
test/unit/test_HNF.cc
test/unit/test_LIAInterpolation.cc
test/unit/test_LRAInterpolation.cc
test/unit/test_Matrix.cc
test/unit/test_Model.cc
test/unit/test_SubstitutionBreaker.cpp

This prevents memory leaks when the caller does not free the received char*. 
It also makes the methods easier to use.

Change printing methods to return string instead of char*

---

src/tsolvers/egraph/UFInterpolator.cc
src/tsolvers/egraph/UFInterpolator.h

`CGraph::edges` is a vector of raw pointers, but it owns the objects.
The objects were correctly deleted when all edges are removed, but not
when a single edge is to be removed.
Later we can come up with a better design, but for now we simply delete the edge
before we remove it from our vector.
I was originally worried that `UFInterpolator` accesses the removed edge after `splitEdge`, but that's not the case, since `splitEdge` correctly sets the new edge for the source node and this new edge is then used. So deleting the edge is fine.
While browsing the code, I noticed a couple of small problems with the code (mostly style), so I am including also a small cleanup here.

UFInterpolator: Fix memory leak and cleanup

---

src/tsolvers/lasolver/Matrix.h
test/unit/test_HNF.cc
test/unit/test_Matrix.cc

`ArithLogic` is not needed for `Matrix` class and can be removed.
Additionally I made small refactoring in the unit tests related to this class.

Matrix: Remove redundant member

---

.circleci/config.yml
ci/run_travis_commands.sh
regression_models/bin/run-and-validate.sh

This include the following changes:
CentOS specific:
- Use gcc-8 instead of gcc-7 on CentOS
- Add DEBUG build on CentOS
- Build newer version of `flex` manually
- Install newer version of `cmake` instead of compiling it from source
Others:
- Rename environmental variable used `INSTALL` -> `OSMT_INSTALL` (to prevent name clash in `flex` build)
- Use more sanitizers in Clang Debug build
- Create and delete `build` directory in the common script instead of having individual CI steps

CI: Update and cleanup the scripts

---

src/parsers/smt2new/CMakeLists.txt

flex versions < 2.6 are not compatible with c++17

fix: bump minimum required flex to 2.6

---

src/tsolvers/lasolver/Tableau.cc

Instead of remembering pointers to problematic variables, can can
remember the variables themselves. Then, instead of building a separate
polynomial and updating the row in one go, we can update the row for
each variable the same way we do in pivoting.
The new way avoids the need for a temporary polynomial which caused
unnecessary memory allocotations as we were gradually building it.
On the other hand, we are now updating the same row multiple times.
It is not immediatelly clear which approach is better, but the
experiments suggest this is a good idea.

Tableau: Simplify normalization of rows

---

src/tsolvers/lasolver/CutCreator.cc
src/tsolvers/lasolver/CutCreator.h

This is what the cuts-from-proofs (after the minor comments) would look like if we used `uint32_t`.

Cuts-from-proofs: Use uint32_t for matrix indexes

---

src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/CoreSMTSolver.h
src/smtsolvers/GhostSMTSolver.cc
src/smtsolvers/TheoryIF.cc

The `forced_split` literal does not seem to be necessary anymore.
Experiments on QF_LIA suggest this is even positive change for the LIA solver.

CoreSMTSolver: Remove forced_split field

---

regression_itp/trivial-proof-A.smt2
regression_itp/trivial-proof-B.smt2
src/options/SMTConfig.cc
src/options/SMTConfig.h
src/proof/PG.h
src/proof/PGBuild.cc
src/smtsolvers/Proof.h

This PR begins a series of changes to interpolation-related code that aims to separate interpolation algorithm from the proof data structure in order to support proof-preserving interpolation needed for theory combination and LIA cuts-from-proofs.
Here the focus is on refactoring the initial resolution proof construction process: `ProofGraph::buildProofGraph`.
One point is important: We remove the code related to structural hashing during the proof construction.
The rationale is that this code has not been exercised for years and it is difficult to understand and complicates the reasoning about the proof construction code.
The interpolation has been working well without it.

Proof: Cleanup of proof building process

---

src/api/smt2tokens.h
src/bin/Interpret.cc
src/logics/ArithLogic.cc
src/logics/ArithLogic.h
src/logics/Logic.cc
src/logics/Logic.h
src/models/ModelBuilder.cc
test/unit/CMakeLists.txt
test/unit/test_NameProtection.cc

If, e.g., a boolean variable in smt-lib has a name consisting entirely of digits, the term printing system incorrectly leaves the variable unquoted.  This PR suggests a fix for the problem.

Logic: fix quoting of variable names which start with numbers

---

src/tsolvers/egraph/UFInterpolator.cc
src/tsolvers/egraph/UFInterpolator.h
test/unit/test_UFInterpolation.cc

UF theory conflict is caused by a disequality and a chain of (possibly
derived) equalities.
Previously, the code was assuming that it will find positive version of
the disequality in the labels map (unless the conflict is between two
interpreted constants). This assumption is not true if the disequality
is actually derived from a distinct term.
The fix is to consider also the possibility of presence of distinct
terms.
Fixes #432

UFInterpolator: Fix interpolation in the present of distincts

---

regression_itp/bug_mask_ite.smt2
regression_itp/bug_mask_ite_nested.smt2
regression_itp/dec-far1.smt2
regression_itp/dec-far2.smt2
regression_itp/distinct_unsat.smt2
regression_itp/itp_bug.smt2
regression_itp/itp_bug_small.smt2
regression_itp/part_bug.smt2
regression_itp/preint-options.smt2
regression_itp/trivial-proof-A.smt2
regression_itp/trivial-proof-B.smt2
regression_itp/uf_bug.smt2
regression_itp/uf_duplicates.smt2
regression_itp/uf_itp_problem.smt2
regression_itp/uf_local_colors_insufficient.smt2
src/api/PartitionManager.cc
src/api/PartitionManager.h
src/proof/InterpolationContext.cc

This PR suggests to switch from external to internal interpolant validation with the aim of enabling interpolant validations in our regression tests.
The successful interpolant validation is asserted, so any violation in our regression test suite will be caught in CI.
This already caught a problem in how we determine how the input formula is split into A and B part.
For now, the validation is enabled only on some benchmarks in our suite, as there are still problems with validation of path interpolants or interpolants in incremental mode. This I plan to address in other PRs.

Enable interpolant validation in regression tests

---

src/logics/ArithLogic.cc
src/logics/ArithLogic.h

In ArithLogic::mkPlus, when combining linear terms with the same variable, we collect the constants from all such terms. Then we need to sum these constants together. Instead of calling mkPlus again, we can directly call the constant simplification procedure, as we know that all the terms we are trying to sum must be numeric constants.
This saves some unnecessary vector copying.
I also suggest to move the simplification helpers into the `.cc` file, so we don't expose them unnecessarily.

ArithLogic: Use direct simplification for sum of constants

---

src/rewriters/Rewriter.h
src/rewriters/Substitutor.h

The machinery of Rewriter is general, but also not optimal for simple
rewritings. Most importantly, it allocates a boolean mask (represented with
vector) to keep track of processed terms. This allocation is often
wasteful a should probably be re-thought.
Here we optimize Substitutor (a sub-class of Rewriter) to avoid the
general machinery when the term to process is a variable.
In this case, the general algorithm can be replaced by a simple lookup
in the substitutions map.

Substitutor: Optimize substitution application to variables

---

src/tsolvers/egraph/UFInterpolator.cc
src/tsolvers/egraph/UFInterpolator.h

It's hard to follow the code on the edge operators, since `CNode::next` is the edge that points from a `CNode` to its successor and not the successor itself.  This PR renames `CNode::next` -> `CNode::edge`.  In addition there is a small refactoring: `addCNode` returns the added `CNode`, which allows skipping a lookup on a map..

Clarify the UF interpolation code

---

CMakeLists.txt
cmake_modules/FindGMP.cmake

Here is my take on how to force CMake to prefer static over shared GMP library, if we want to.
This is useful for creating statically linked executables.

CMake: Add an option to prefer static GMP libraries

---

src/common/CMakeLists.txt
src/common/TreeOps.h
src/logics/Logic.h
src/rewriters/Rewriter.h

This PR suggests 2 ways to optimize memory usage in Rewriter:
1. The auxiliary vector for marking processed terms can be reused. I suggest to put it in `Logic` as it can be re-used for other purposes as well. Using `nat_set` instead of `vec` has the advantage that it can be cleared in constant time.
2. When building a new version of the term with rewriting already applied to its children, we need to collect the new children. Previously we were constructing new vector for every term, we can re-use a single vector for the whole rewriting process.

Rewriter: Optimize memory (re-)usage

---

src/common/TreeOps.h

Avoid data structure initialisations when visit is called on a variable, similar to rewriter.

TermVisitor: implement the variable-optimisation

---

src/common/TreeOps.h
src/logics/Logic.cc
src/logics/Logic.h
src/rewriters/Rewriter.h

We can hide the implementation details of using nat_set and provide a nicer interface (especially the constructor takes care of setting up the  low-level data structure) for term markings.
We can also mark the nat_set mutable (basically not considering it a logical part of the Logic state) and thus allowing the method for creating TermMarks helper constant on Logic.

Logic: Use wrapper with nicer interface for term marking

---

src/logics/Logic.cc
src/logics/Logic.h

Right now I see no reason why the abstract value counter, used for getting unique names for values in uninterpreted function models, should be a global variable.  This PR suggests to turn it into a member of `Logic`.

Logic: make abstract value counter member of logic

---

regression_itp/proof_duplicate_literals.smt2
src/api/PartitionManager.cc
src/api/PartitionManager.h
src/common/VerificationUtils.cc
src/common/VerificationUtils.h
src/proof/InterpolationContext.cc

This PR continues the work of #441 and enables internal validation of path interpolation property.
It also implements missing functionality in `PartitionManager` to return any subset of top-level asserted formulas, which is needed to validate path interpolants.

Enable validation of path interpolants

---

src/api/PartitionManager.cc
src/common/TreeOps.h
src/common/VerificationUtils.cc
test/unit/CMakeLists.txt
test/unit/test_Ites.cc
test/unit/test_Visitors.cc

This PR adds a generic visitor for collecting subterms of a term, templated by a predicate the subterms need to satisfy.
Two helper methods are added for collecting all subterms and for collecting all variables.
This follows the pattern of uniting all operations on terms on our base `Visitor` and `Rewriter`.
Some existing methods are marked as deprecated and I suggest to remove them in the future. This is subject for discussion.

Terms: Add generic subterms collector

---

src/bin/Interpret.cc

Give an error messge if `get-value` is called, but the solver is not in
a satisfiable state.  The new behaviour is consistent with `get-models`.

Interpret: error on get-value if in non-sat state

---

ci/build_maximally_static.sh

CMake can be instructed to build the project with the build system that has been used in configuration.
For example, I now use ninja as the default build system in CMake, so
the script did not work for me before.

CI: Make build script build-system-agnostic

---

src/common/CMakeLists.txt
src/common/Random.h
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/CoreSMTSolver.h
src/smtsolvers/GhostSMTSolver.cc
src/smtsolvers/ScatterSplitter.cc
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h

The LIA solver, upon finding a solution to the linear system assigning non-integer values to integer variables, needs to communicate to the SAT solver how to fix a value to an integer.  Previously this was done by choosing the variable to be fixed by choosing the one furthest away from an integer.  It turns out that a completely random heuristic is better than the previous heuristic.  While we are trying to find a better heuristic, this PR suggests to switch to a completely random heuristic.

Lia random splitting

---

src/logics/ArithLogic.h

LANonlinearException was previously written weirdly.  This commit
suggests an improvement that is hopefully more standard.
Co-authored-by: Antti Hyvarinen <antti.hyvarinen@gmail.com>

ArithLogic: Fix the LANonlinearException logic

---

src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h
src/tsolvers/lasolver/LAVarMapper.cc
src/tsolvers/lasolver/LAVarMapper.h

`LAMapper` stores two mappings:
1. For each `Pterm` that corresponds to arithmetic term the corresponding LVRef (Simplex variable)
2. For each `Pterm` that corresponds to arithmetic inequality the LVRef of the arithmetic term that is compared to a constant.
The second mapping is redundant. Given the inequality we can extract the term from the inequality and just ask for the representation of that.
This does not makes a big difference in single query context, but in scenarios such as in Golem, where new terms are created all the time, the initialization of the LASolver can actually spend a lot of time in creating the second mapping. The reason is that the mapping is represented by a vector and the initialization must `push` as many times as is the `id` of the inequality. In long runs there …

LASolver: Remove redundant storage of information

---

benchmark/performance/CMakeLists.txt
benchmark/performance/perf_RationalEfficiency.cc
benchmark/performance/perf_mkTerms.cc

This PR adds benchmarking tests for creation of conjunctions.
There are tests for
1. Creating a lot of binary conjunctions
2. Creating one larger conjunction
In both cases, I added tests evaluating the impact of negated terms and in the second case comparing an ordered arguments and randomly shuffled arguments.

Benchmark: Add benchmarking of simple term creation

---

benchmarking/README.md
benchmarking/compare.sh
benchmarking/save-benchmark.sh

Scripts for comparing benchmarks.  I'll write later a readme, and we can think of something nicer.  The problem is that I want to store the benchmark binaries to be able to run them later on one go, but the benchmarks link on the opensmt library that is currently in the `build` directory.

benchmarking: first version of the scripts

---

benchmark/performance/CMakeLists.txt
benchmark/performance/perf_mkTermsBigConj.cc
benchmark/performance/perf_mkTermsSmallConj.cc

This PR
* splits the mkTerms benchmark into two so that benchmarks in the same order of magnitude are run together, and
* uses shorter benchmark names so that plotting them in a readable way is nicer.

Split perf_mkTerms to two

---

src/common/TreeOps.h
src/parallel/ScatterSplitter.cc
src/parallel/ScatterSplitter.h
test/unit/test_Visitors.cc

When parallel solver needs to communicate terms they are serialised at the moment into smt-lib terms.  However, these terms might grow huge.  This PR suggests how the size can be kept in check using the number of sub-terms as a proxy for the smt-lib size of the term.

Avoid serialising big terms into smt-lib

---

src/logics/ArithLogic.cc

Since OpenSMT uses multiplication by -1 to express negated arithmetic
terms, this operation can occur quite often and is repeated for example
when applying substitutions.
Multiplication by -1 can be done more efficiently by negating the second
argument (as opposed to full mkTimes run).

ArithLogic: Handle multiplication by -1 as negation

---

regression_models/instances/uflra_printing.smt2
src/api/Interpret.cc

Logic::pp should not be used for output to the user.
It prints rationals in infix format, but models should be printed in SMT-LIB format (using Logic::printTerm).

Interpret: Fix printing of models for functions

---

.circleci/config.yml

Apparently, CircleCI is deprecating the image we are currently using: https://discuss.circleci.com/t/xcode-image-deprecation/44294

CI: Update MacOS image

---

src/itehandler/IteToSwitch.h

I believe previously `iteNodeWord32Size` was computing the size in bytes, not size in 32-bit chunks.

ITE: Use appropriate memory in NodeAllocator

---

src/logics/Logic.cc

After updating OpenSMT to latest release in Golem, I got some unit tests failing at a very weird place.
I tracked down the problem to uninitialized value of sort symbol `sym_ArraySort` (when `Logic` does *not* support arrays).
The code was not consistent before because it only creates array sort if the Logic does not have arrays, but the check for array sort in `Logic::getSort` is unconditional.
Thus, it is a check against uninitialized value.
This PR fixes to problem by initializing the symbol sort to `SSymRef_Undef` if the logic does not support arrays.

Logic: Fix unintialized sort symbol

---

src/api/MainSolver.cc
src/cnfizers/TermMapper.h
src/common/VerificationUtils.cc
src/common/VerificationUtils.h
src/proof/InterpolationContext.cc
src/proof/InterpolationContext.h
src/proof/PG.h
src/proof/PGBuild.cc
src/proof/PGCheck.cc
src/proof/PGMain.cc
src/proof/PGPrint.cc
test/unit/test_LIAInterpolation.cc
test/unit/test_LRAInterpolation.cc
test/unit/test_Proof.cc
test/unit/test_ResolutionProofInterpolation.cc
test/unit/test_UFInterpolation.cc

This PR removes some of the unused fields and methods in `ProofGraph` and also removes the last usage of implication verification using external tool.
Internal verification should be sufficient in my opinion.

Small cleanup related to resolution proof graph

---

.circleci/config.yml

I got an error in my other PR in `starexec` build, because of failing to install new `CMake`.
I found that upgrading `pip` should help.

CI: Upgrade pip on CentOS before using

---

src/itehandler/IteHandler.cc
src/itehandler/IteHandler.h
src/logics/ArithLogic.cc
src/logics/ArithLogic.h
src/logics/Logic.cc
src/logics/Logic.h
src/rewriters/DivModRewriter.h
test/unit/test_Ites.cc
test/unit/test_LIALogicMkTerms.cc

Currently when we print terms there is no support for avoiding printing internal auxiliary expansion variables (currently `.ite`, `.div`, `.mod`).  This is a problem when terms need to be communicated to other solvers, and seems to cause (soundess) problems also if the terms are communicated within different opensmt instances.
This PR introduces reverse operators that allow expressing terms using the original terms defined over the input vocabulary.  This is done by syntactically obtaining the PTRef number from the symbol name and running a rewriter-based dag-traversal.

Implement "reverse operators" for auxiliary variables

---

src/api/MainSolver.cc
src/api/MainSolver.h

Remove a historical flag that was used at some point in relation to the abandoned opensmt binary format.

MainSolver: Remove unused flag

---

src/simplifiers/BoolRewriting.h
test/unit/test_Rewriting.cc

Previously, if rewriteMaxArity encountered a connective different than
conjunction or disjunction, it would automatically keep the term as it
was. This is not correct, because some rewriting might have already
happened in the subterms, so this term should also be rewritten
accordingly.

Rewriting: Fix missing rewrites in rewriteMaxArity

---

src/common/FastRational.cc
src/logics/Logic.cc
src/proof/PGBuild.cc
src/smtsolvers/LookaheadSMTSolver.cc
src/smtsolvers/SimpSMTSolver.cc
src/smtsolvers/TheoryIF.cc

It seems that some clang versions (14?) complain in our code where we are using `&` instead of `&&` (or `and`) when compiled with `--Wall -Wextra -Werror`.  I believe that the code should be using `and` in this case, so this PR suggests the fix.

Style fixes pointed out by more recent compilers with `--wall -Wextra -Werror`

---

src/bin/opensmt.cc

It came to my attention that these flags are not present in all Linux environments, which could result in compilation errors.
It seems this was encountered also in MiniSAT some time ago: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=590254
I don't know what is the way to fix it, so here I am proposing to just remove this piece of code.

Remove FPU control flags

---

.circleci/config.yml

The tag we used for the stable build is deprecated in circleci.  This PR suggests to switch to a tag that is updated more often and hopefully helps us to keep opensmt building in modern debians.

Update `build-recent` to use the image `cimg/base:current`

---

.circleci/config.yml

This PR proposes the use of custom-built docker images in opensmt.  This should bring the build times down especially since the model validation environment doesn't need to be compiled every time.
In addition, the PR suggests to split the jobs into smaller jobs, one for each `(compiler, build type)` combination.

Build image update

---

src/tsolvers/ArrayTHandler.cc
src/tsolvers/IDLTHandler.cc
src/tsolvers/LATHandler.cc
src/tsolvers/RDLTHandler.cc
src/tsolvers/THandler.cc
src/tsolvers/TSolverHandler.cc
src/tsolvers/TSolverHandler.h
src/tsolvers/UFLATHandler.cc
src/tsolvers/UFTHandler.cc

Currently the order dictated in which solvers should be accessed, e.g., when asserting literals, is defined in a vector `TSolverHandler::SolverSchedule`.  However, the code does not respect this order.  Instead the code uses an order that is non-deterministic between systems as it depends on in which order certain static data structures are initialised.
This commit fixes the code to follow strictly the order from `TSolverHandler::SolverSchedule`.  As a result of the cleanup, we get rid of an extra data structure in `TSolverHandler` that was used to store the solvers based on their IDs.
Fixes #556.

Tsolverhandler cleanup

---

src/logics/ArithLogic.cc

These are two, hopefully not controversial, simplifications of the code in ArithLogic operations.
See the commit messages for details on each.

ArithLogic: Small simplifications

---

src/api/Interpret.cc
src/api/Interpret.h
src/pterms/PtStructs.cc
src/pterms/PtStructs.h

Since the introduction of `Model` class, we have not been not using `ValPair` anymore.
I believe it can be safely removed now.

Pterms: Remove now redundant struct ValPair

---

src/logics/Logic.cc
src/logics/Logic.h
src/tsolvers/egraph/EnodeStore.cc
src/tsolvers/egraph/EnodeStore.h

I wanted to do a small refactoring of symbols in OpenSMT and the `anon` symbol was causing some trouble for that.
The Egraph solver can work without this artificial symbol, so it should safe to remove it.
Previously, it was used to create special Enodes that do not need to represent the children of the corresponding Pterm.
However, it seems to be that these special Enodes can use the symbol of the Pterm without losing any effect on the program.

Remove the ad-hoc 'anon' symbol

---

.clang-files
.clang-format
src/rewriters/DistinctRewriter.h
src/rewriters/DivModRewriter.h
src/tsolvers/lasolver/Tableau.cc
src/tsolvers/lasolver/Tableau.h

This PR changes a rule to disallow function definitions on a single line, unless this is a inline definition in a class body.
The modified rules are then applied to `src/tsolvers/lasolver/Tableau.{h,cc}`.

Clang-format: Apply to Tableau files

---

src/pterms/Pterm.h

Pterm's arguments should never be changed once the term is created. Hence, it does not make sense to return an argument by reference. Additionally, PTRefs are small enough to be returned by value instead of by const reference.

Pterm: Return arguments by value

---

src/logics/ArithLogic.cc

Equalities are currently normalized to form c = t where c is a constant and t is a term.
When computing polynomial from the equality, we compute the term t - c.
However, mkMinus currently works by negating the SECOND argument and passing them to mkPlus.
It is better to negate the constant rather than the term, thus we should pass FIRST argument of the equality as the SECOND argument to mkMinus.
Additionally, we can avoid the whole operation if the constant is 0.

ArithLogic: Avoid redundant work when computing substitutions

---

src/logics/Logic.cc

Previously, Logic::mkBinaryEq would make a call to PtStore::lookupSymbol to retrieve proper equality symbol for the arguments. However, Logic already caches equality symbol for each sort. Thus we can just look into this cache to retrieve the proper symbol.

Logic: Replace expensive method call with a lookup

---

src/logics/Logic.cc
src/symbols/SymStore.cc
src/symbols/SymStore.h
src/symbols/Symbol.h

Previously, the implementation detail that stores the return sort in the same array as arguments sort leaked out up to Logic's creation of new function declaration.
It seems more natural and cleaner to keep the return sort explicitly separated from arguments' sorts up until the last moment.
This also avoids some unnecessary memory allocations.

Symbols: Use interfaces with explicit return sort

---

src/logics/ArithLogic.h
src/tsolvers/lasolver/LASolver.cc

This method is a relict from the time when we tried to keep ITEs around and let the theory solver deal with them. That did not work and we now eliminate ITEs from the formulas before they are internalized. Thus LASolver should never encounter an ITE.

ArithLogic: Remove method isNumVarOrIte

---

src/logics/ArrayTheory.cc
src/logics/Logic.cc
src/logics/Logic.h
src/tsolvers/axdiffsolver/ArraySolver.cc
src/tsolvers/axdiffsolver/ArraySolver.h

Methods isArrayStore and isArraySelect were missing the overloads taking PTRef as argument. This adds these overloads  to accompany the existing methods taking SymRef as argument.

Arrays: Add helper methods for querying array terms

---

src/tsolvers/lasolver/Simplex.cc

If the current value of a variable is above upper bound, the message should say exactly that.
Similarly if the current value is below lower bound.

LASolver: Make debug print clearer

---

src/tsolvers/egraph/Egraph.h
src/tsolvers/egraph/EgraphSolver.cc

This is just a tiny optimization to avoid some calls to Logic::mkNot. Instead of storing information for the negated terms, we can store the same information for the positive term and then we do not need to lookup the negated term first.

Egraph: Avoid unnecessary mkNot calls

---

src/api/Interpret.cc
src/api/Interpret.h

Last changes in parseTerm (a838804c) led to increased size of activation record and this resulted in more stack overflows on SMT-LIB benchmarks with huge nested lets.
Even though according to my intuition, the abovementioned changes should have decreased the memory footprint on the stack, it seems the opposite happened. My guess is that the changes allowed compiler to inline something that was not inlined previously, but this required more stack space to accomodate the inlined code.
The changes in this PR move more work (and data structure) to another method, which is then not inlined anymore (my guess). This not only reverts the size increase, but actually leads to further decrease of the activation record's size.
Proper solution would be to reimplement parsing in a non-recursive way, …

Interpret: Reduce size of call stack's activation record for parseTerm

---

src/api/Interpret.cc

This ensures stdout is flushed.
Fixes #615

Interpret: Use cout to print get-value response

---

src/logics/ArithLogic.cc
src/logics/ArithLogic.h
test/unit/test_LIALogicMkTerms.cc
test/unit/test_LRALogicMkTerms.cc

Previously we were normalizing equality (almost) the same way as inequality. However, while for inequality it is possible that the right-hand-side can have both positive and negative leading term, for equality this meant that the same equality can be normalized to two different terms.
For example "x = 2" got normalized to "-2 = -x", while "2 = x" got normalized to "2 = x".
The proposed fix here is to ensure that the equalities always have positive leading term on the right-hand-side. Thus now even "x = 2" is normalized to "2 = x".

ArithLogic: Fix normalization of equality

---

src/logics/ArithLogic.cc
src/logics/ArithLogic.h
test/unit/test_LIALogicMkTerms.cc

OpenSMT computes incorrectly `(mod x 1)`, `(mod x -1)`, `(div x 1)` and
`(div x -1)` because the special handling for these is missing.  This
PR adds the simplifications directly to `ArithLogic`.
There's also unit tests for the above cases. 
Fixes #628

Fix mod corner cases

---

examples/test_arrays.cc
src/logics/Logic.cc
src/logics/Logic.h
src/sorts/SStore.cc
src/sorts/SStore.h
test/unit/CMakeLists.txt
test/unit/test_Arrays.cc

This PR adds an example how to create (and check) formula on the theory of arrays. In order to do that, we extend API of `Logic` to provide an easy way to get an array sort with the given domain and codomain.

Arrays: Add example of API usage

---

src/tsolvers/egraph/EnodeStore.cc
src/tsolvers/egraph/EnodeStore.h

A map from `ERef` to `PTRef` is redundant since `Enode` itself remembers its corresponding `PTRef` a `Egraph` can access this information given `ERef`.

EGraph: Remove redundant mapping

---

src/api/Interpret.cc
src/api/Interpret.h
src/api/MainSolver.cc
src/api/MainSolver.h
src/api/smt2tokens.h
src/parsers/smt2new/smt2newlexer.ll

I believe this functionality is no longer needed.
I did not find the corresponding read state functionality. Maybe we removed that already some time ago?

Remove functionality to dump solver state

---

src/logics/Logic.cc

Instead of using a hard-to-read table, let's follow the standard to the letter. The standard defines which characters are permitted in the simple symbol (which does not require quotes). If we encounter a character not in the specified set, we need to add quotes.
The reason for this change has been moivated by compilation problem in JavaSMT and the fact that even though the table was created with length 256, only the first 250 entries were specified.

Logic: Make test for quotes more transparent

---

src/logics/Logic.cc
src/pterms/PtStore.cc
src/simplifiers/BoolRewriting.cc
src/tsolvers/egraph/EnodeStore.cc

With gcc 14 some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. In opensmt's case it is the `<algorithm>` header.
[Downstream Gentoo bug](https://bugs.gentoo.org/916855)
[GCC 14 porting guide](https://gcc.gnu.org/gcc-14/porting_to.html)

Add include <algorithm> to fix building with gcc 14

---

src/logics/Logic.cc

Creating array sorts should be allowed only for logics that support arrays.

Logic: Make API for getting array sort more robust

---

src/minisat/mtl/Map.h

Just some minor changes in constructors of some minisat classes which were in deprecated form and invalid since C++20.
The whitespace changes are just automatic trimming of trailing WS by my editor.

maintained C++20 compatibility

---

src/api/Opensmt.cc
src/api/Opensmt.h
src/cnfizers/Tseitin.h
src/logics/ArrayTheory.h
src/logics/BVLogic.cc
src/logics/BVLogic.h
src/logics/LATheory.h
src/logics/Logic.cc
src/logics/Logic.h
src/logics/Theory.h
src/proof/InterpolationContext.cc
src/proof/PG.h
src/smtsolvers/Proof.h
src/smtsolvers/SimpSMTSolver.cc
src/smtsolvers/SimpSMTSolver.h
src/sorts/SStore.h
src/tsolvers/ArrayTHandler.h
src/tsolvers/THandler.h
src/tsolvers/UFLATHandler.h
src/tsolvers/UFTHandler.cc
src/tsolvers/UFTHandler.h
src/tsolvers/axdiffsolver/ArraySolver.h
src/tsolvers/bvsolver/BVSolver.cc
src/tsolvers/bvsolver/BVSolver.h
src/tsolvers/stpsolver/STPSolver.h
src/tsolvers/stpsolver/STPSolver_implementations.hpp

I experienced in my project that some classes in OpenSMT have implicitly deleted move semantics. I found out that because my class forbids copying and requires moving, but class `Opensmt` was not able to.
I observed that this is caused by a user-defined destructor, referring to [rule of five](https://en.cppreference.com/w/cpp/language/rule_of_three): "the presence of a user-defined (or = default or = delete declared) destructor, ... prevents implicit definition of the move constructor and the move assignment operator". This also means that wherever move semantics are desired (e.g. using `std::move`), the object is actually still copied because move constructor is not available. Therefore, performance can be possibly improved: "failing to provide move constructor and move assignment is …

Got rid of useless (actually possibly harmful) default destructors

---

src/api/MainSolver.h
src/api/Opensmt.h
src/cnfizers/Cnfizer.h
src/logics/ArithLogic.h
src/logics/Logic.h
src/minisat/mtl/Map.h
src/options/SMTConfig.h
src/symbols/SymStore.h

Allows to move the main solver in applications that require it (e.g. if they use `std::unique_ptr<Opensmt>` and do stuff with it). This required to provide move semantics in several nested/used classes, using the rule of five.

Provided move semantics for `Opensmt`

---

src/common/FastRational.h

I noticed that it may be the first time using `std::optional` in the project but I hope it won't cause any trouble..
- `force_ensure_mpq_valid` is `const`, uses `const_cast`, but may modify non-mutable data members of `FastRational`, which I am afraid results in [undefined behavior](https://en.cppreference.com/w/cpp/language/const_cast)
- I also changed `FastRational` to `opensmt::Number` in `ArithLogic.h` to maintain consistency - the header includes only the abstraction `Number.h` and is using it in the declaration of several functions but not all. I also changed that in most cases in `ArithLogic.cc`, but not in all. I observed that many pieces of code in OpenSMT assume that `FastRational` is being used in the place of `Number`, so changing it to `mpq_class` would break a lot of code. …

Getters of numerator and denominator for `FastRational`

---

src/common/FastRational.cc
src/common/FastRational.h

Casting away const and then modifying the object is UB if the original object was const.
From [cppreference](https://en.cppreference.com/w/cpp/language/const_cast):
"Modifying a const object through a non-const access path results in undefined behavior."
We fix the problem by making `mpq` and `state` mutable, as we can change the inner representaton in certain circumstances without changing the rational value represented by the object.
Fixes #662.

FastRational: Eliminate potential UB

---

.gitignore
Makefile
README.md

Root Makefile that serves only for initial builds.
`make` (or `make default` or `make release`) builds `build` and `make debug` builds `build-test`.
`make all` builds both.
Once the build directory is created, the rule is "up-to-date" and not run anymore. This is not a mistake but my intention.
The build directories can also be removed using `make clean` (or `make clean-release`) and `make clean-debug` (or `make clean-all`). Then it is possible to run e.g. `make` again.
The target build directories can be modified via cmdline, for example: `make RELEASE_BUILD_DIR=build-release`.
But then the option should also be used for `make clean` otherwise it will try to remove the default build directory (it won't fail but won't do anything).
More importantly, CMake options may be modified using …

664 explicitly divide debug and release builds

---

src/logics/Logic.cc

Fixes #694.
When opensmt processes assertions involving empty name, it triggers an assertion failure in `Logic::mkConst`.
To resolve this issue, I propose a modification to the `Logic::mkConst` to check for empty name explicitly. If an empty name is encountered, the function will now print an error message and return `PTRef_Undef`.

Improve Handling of Empty Name in Logic::mkConst

---

.circleci/config.yml

CircleCI is shutting down its Intel-based OSX images and moving to M1-based images.
See: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

CI: Update OSX resource

---

src/logics/ArrayTheory.cc
src/logics/UFLATheory.cc
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/CoreSMTSolver.h
src/smtsolvers/TheoryIF.cc
test/unit/test_UnsatCore.cc

This PR enables computation of unsat cores for theory combination by supporting computation of resolution proof for theory combination.
This builds on top of changes in #706, which enables per-partition preprocessing.
Besides preprocessing changes, the only missing feature seemed to be handling unit clauses at level 0 computed from splits (theory combination lemmas for interface variables), which is added in this PR (see the corresponding commit message for details).

Add support for unsat core computation for theory combination

---

src/tsolvers/arraysolver/ArraySolver.cc

This is just a tiny optimization to not repeat the same work inside a loop when we can do it once before the loop.

ArraySolver: Tiny performance optimization

---

CMakeLists.txt
examples/CMakeLists.txt
src/api/CMakeLists.txt

The latest version of CMake at the time of writing is 3.30 and it warns that
"Compatibility with CMake < 3.5 will be removed from a future version of
CMake."
We need to bump the required CMake version at least to 3.5. However, we have at a few places some configuration that requires CMake >= 3.12. I think it reasonable to bump the required version to that version and simplify our scripts a bit.

CMake: Bump required version of CMake

---

.clang-format
src/cnfizers/TermMapper.cc
src/cnfizers/TermMapper.h
src/rewriters/Rewriter.h
src/tsolvers/lasolver/Tableau.cc
src/tsolvers/lasolver/Tableau.h

- `Standard: c++20`, `AlignOperands: AlignAfterOperator` and `NamespaceIndentation: All` do not affect the current files
- `QualifierAlignment: Right` has not been enforced yet but we seem to follow this guideline
- `AlwaysBreakTemplateDeclarations: Yes` changed a few places, but I believe that this setting is much easier to read, especially with the possibility of using C++20 concepts
Reference: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

added more rules to clang-format

---

CMakeLists.txt
cmake_modules/FindGMP.cmake

Apparently, order of static libraries when linking into executable can matter, and for GMP the C++ version gmpxx must come before the C version gmp.
On some systems (like Fedora, ArchLinux), this was not the cases, most likely because when creating the wrapper target GMP::GMP, we specified the libraries in the wrong order.

CMake: Remove workaround and fix order of GMP libs

---

.circleci/config.yml

There is a bug in older versions of clang-format. Using the latest Ubuntu image fixes the problem.

CircleCI: used latest Ubuntu for clang-format

---

.circleci/config.yml
src/tsolvers/stpsolver/IDLSolver.h
src/tsolvers/stpsolver/RDLSolver.h

The latest Ubuntu image was still not enough for `clang-format` (#744)
See this [PR](https://github.com/usi-verification-and-security/verify-env/pull/6) on `verify-env`.

CircleCI: used latest Arch Linux for clang-format

---

src/tsolvers/egraph/CMakeLists.txt

I am pretty sure we do not need to install UFInterpolator.h, it should not be exposed to consumers.
While removing it, I reorganized the corresponding CMakeLists.txt.

CMake: Do not install redundant file + small cleanup

---

test/unit/test_LRALogicMkTerms.cc

Added additional test that checks the case of creating "1/3" instead of just "1/2".
This can catch errors if the implementation of rationals is changed since 1/3 does not have finite representation if the numerator and denominator are not separated (such as with floats).

Extended test_LRALogicMkTerms:ConstantSimplification of 1/3

---

src/models/CMakeLists.txt

ModelBuilder is an internal detail of how OpenSMT builds SMT models. Users should only have access to the final Model, not to the builder.

Do not expose ModelBuilder

---

CMakeLists.txt
parallel-test/CMakeLists.txt
test/CMakeLists.txt

We update googletest to v1.15.2. As part of that we use `FetchContent_MakeAvailable` to fetch it, because our previous way is now deprecated in CMake 3.30.
In order to use the new command, we need to bump minimal CMake version to `3.14`

CMake: Update minimal version and how googletest is fetched

---

src/logics/CMakeLists.txt
src/logics/Theory.h
src/tsolvers/CMakeLists.txt

We can revive these files if #601 is successfully finished.
However, currently we do not support any way for the user to use BV solving, so it does not make sense to keep compiling these files.

Disable compilation of BV-related files since we do not support BV solving at the moment anyway

---

src/api/Interpret.cc
src/common/ScopedVector.h
src/common/TermNames.h

It is often necessary to iterate over all pairs of names and terms of `TermNames`. Previously this was done by looking up the term for each name, which is inefficient. The proposed method has just linear complexity of such iterations.
Furthermore, the PR offers to also iterate only over names or only over terms, which, if the pairs are not desired, is even more efficient.

Efficient iterating and views on `TermNames`

---

src/logics/Logic.cc

I really do not know why it was previously sorted in descending order.
It seems to be an old line of code from the times before versioning using GitHub.
I only found that xors are handled in `Tseitin.cc` and `Logic.cc:getNewFacts`, but it does not seem that the order has any special meaning...
I believe that the fix should be just fine.

Sorting xor-args in ascending order (same as others)

---

src/rewriters/DivModRewriter.h

The comment incorrectly used `dividend` instead of `divisor` when formulating the condition on modulo.
Also, we should assert not only that the divisor is a constant, but it is an integer constant.

Rewriters: Fix typo in a comment and add assertion

---

.github/workflows/release.yml
ci/build_for_release.sh

This adds a GitHub action that we can use to automatically build and upload binaries once a release is published.
The drafting of the release and its publication is still manual, but that is OK since we want to have control over that process.

Add Github action for release

---

.circleci/config.yml

We require that the linkage of the produced binary contains no dynamic libraries. For that, we use the exit status of `ldd` (since it is Linux), which fails if no dynamic libraries are present. Hence we negate the exit status with `!`.

CI: check that the static Linux build is indeed static

---

src/api/MainSolver.cc
src/api/MainSolver.h
src/parallel/MainSplitter.cc

Consistently referring to "assertion stack" (from SMT-LIB 2.6) within the API of `MainSolver` instead of "frames" which is not known outside of OpenSMT community.
I also added methods to access assertions of the assertion stack. The API offers both a copy of all the assertions and also just a view to the assertions, which is more suitable when one wants to just iterate over the assertions of get their count. However, the view is not implemented yet.

`MainSolver` API for assertion levels of the assertion stack

---

src/api/Interpret.cc
src/api/MainSolver.cc
src/api/MainSolver.h
src/common/TermNames.h
src/unsatcores/CMakeLists.txt
src/unsatcores/UnsatCore.cc
src/unsatcores/UnsatCore.h
src/unsatcores/UnsatCoreBuilder.cc
src/unsatcores/UnsatCoreBuilder.h
test/unit/test_UnsatCore.cc

Also moved printing from `Interpret` to `UnsatCore` and divided minimization into a separate class `Minimize`.

Treat named and full unsat cores separately but with common interface

---

src/tsolvers/lasolver/Polynomial.h

`std::move` does not require that the argument iterators are `move_iterator`s.
(It would be necessary only if `std::copy` was used: [example](https://stackoverflow.com/questions/26432990/are-stdmove-and-stdcopy-identical)).
Furthermore, `move_iterator` should not be dereferenced more than once: [cppreference](https://en.cppreference.com/w/cpp/iterator/move_iterator/operator*).

Removed problematic use of `move_iterator`s

---

.circleci/config.yml

It is important to keep updating the environment, otherwise, homebrew may not have ready-to-pour packages any more (e.g. CMake).

CI: Update macos environment

---

src/models/Model.cc
src/models/Model.h
test/unit/test_Model.cc

This functionality is helpful for Golem and could be interesting for others as well. By adding the possibility of extension, we do not need to expose ModelBuilder to the outside world.

Model: Add a simple method to extend a model with value for a new variable

---

scripts/release-tag.sh

Resolves #808 
Extracts full version from `CMakeLists.txt` and creates the corresponding release tag.
Optionally, it also pushes the tag to `origin`.

Helper script to create and possibly push annotated release tag

---

CMakeLists.txt
src/bin/CMakeLists.txt

The build fails with `cmake -DBUILD_EXECUTABLES=OFF ..` because the definition of `OPENSMT_GIT_DESCRIPTION` is not conditioned by `BUILD_EXECUTABLES` and rule `OpenSMT-bin` does not exist without the parameter.
Hence I moved the definition into the `CMakeLists.txt` that concerns the binary specifically and is already conditioned.

Fixed CMake definition of the executable regarding the version

---

src/common/Random.h
src/common/ScopedVector.h
src/common/SplayTree.h
src/common/numbers/NumberUtils.h

I failed to build OpenSMT as an external library when I swapped the order of `StringConv.h` and `NumberUtils.h`. The reason is that some headers use assertions but do not include `<cassert>`, even indirectly via other headers.

Included `cassert` in standalone headers

---

src/api/Interpret.cc
src/api/Interpret.h
src/api/MainSolver.cc
src/api/MainSolver.h
src/common/TermNames.h
test/unit/test_UnsatCore.cc

Non-const getter `getTermNames` seems necessary only for consecutive `insert` after `insertFormula`.
I consider it clearer to use a function such as `insertNamedFormula` directly, similar to what is done in the SMT-LIB2 format.
This way it is also clearer that the user is *not* responsible for removing the names in incremental queries, this is what `pop` implicitly does.
Instead of directly removing `getTermNames`, I used a deprecated attribute since we changed the API.
However, it causes a lot of warnings because the compiler still favors the non-const getter in many situations, even when the const is sufficient - one would have to use e.g. `std::as_const` to avoid the warning.
Here I am not sure, maybe we should remove the non-const getter right away. It may break existing code after …

Replaced non-const `getTermNames` by `tryAddNamedAssertion`/`tryAddTermNameFor`

---

src/tsolvers/lasolver/LABounds.cc
src/tsolvers/lasolver/LABounds.h
src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h

This commit removes a redundant member `in_bounds` of `LABoundStore` and updates the code accordingly.
This member was used only for initialization, and we don't need it since we can store the bounds directly in the `bounds` member. The initialization also becomes simpler.

LASolver: Simplify handling of bounds

---

src/logics/ArithLogic.cc
src/logics/ArithLogic.h
src/logics/Logic.cc
src/logics/Logic.h

I believe that in none of the cases it is reasonable to have the functions as non-const.

Added missing const modifiers in `Logic` and `ArithLogic` functions

---

src/tsolvers/lasolver/LASolver.cc
src/tsolvers/lasolver/LASolver.h
src/tsolvers/lasolver/LAVarMapper.cc
src/tsolvers/lasolver/LAVarMapper.h

Small cleanup in LASolver.
Include the removal of method `updateBound`.
This method was checking if the given bound (PTRef) has already been processed or not.
However, it was only called in a situation where it is guaranteed that the bound has not been seen before (the theory solver keeps track of processed inequalities with `isInformed` and `setInformed` methods in `LASolver::declareAtom`.

LASolver: Small refactoring

---

src/logics/ArithLogic.h
src/logics/BVLogic.h
src/logics/Logic.cc
src/logics/Logic.h

Current implementation of virtual `Logic::isBuiltinSort` is useless and more importantly error-prone if something is missed, but it is sufficient to observe if the sort symbol was created as `INTERNAL`.
This way, for example, the auxiliary array sort is missed by the current `isBuiltinSort`.
It is probably less performant but probably negligible.
I would BTW also recommend a similar general approach for all other internal symbols, instead of enumerating all possibilities in virtual methods.

Replaced `Logic::isBuiltinSort` by `isInternalSort`

---

src/logics/ArithLogic.cc
test/unit/test_Substitutions.cc

Previously, the test I am adding here would trigger an assertion failure, because it would try to create a substitution `x -> 1/3` in the integer logic.
To prevent that, we can detect such cases and abort the computation of substitutions early. We have to pass along the fact that the formula from which we are computing substitutions is unsatisfiable.

Substitutions: Add detection of conflict in arithmetic substitutions

---

src/bin/opensmt.cc

Similarly to how option `--produce-interpolants` works, we also include SMT-LIB options `:minimal-unsat-cores` and `:print-cores-full` into the command line options.
We do not include `:produce-unsat-cores` because it does not seem to be useful (as discussed below). An alternative is suggested in #845.

Included SMT-LIB unsat-core options into command-line options

---

.clang-files
src/api/CMakeLists.txt
src/api/GlobalStop.cc
src/api/GlobalStop.h
src/api/MainSolver.cc
src/api/MainSolver.h
src/parallel/ScatterSplitter.cc
src/smtsolvers/CoreSMTSolver.cc
src/smtsolvers/CoreSMTSolver.h
src/smtsolvers/LookaheadSMTSolver.cc
src/smtsolvers/SimpSMTSolver.cc
test/unit/CMakeLists.txt
test/unit/test_Stop.cc

Used dedicated functions at the global and local scopes to notify the solver to stop.
Used the flags in `okContinue()` function
Not used in `ScatterSplitter` though, which uses dedicated mechanisms for timeouts etc.
Added a test that demonstrates how to use the stopping mechanism using threads and even a simple timeout.

Unified external stops of solvers

---

src/api/GlobalStop.cc
src/api/GlobalStop.h
test/unit/test_Stop.cc

Also added previously missing `resetGlobalStop()`. I do not implement this at the local scope - it would also have to maintain the consistency of the solver if it was about to be used further.

Fixed unit tests for stopping solvers and made them not depend on concrete runtime
